const { chromium } = require('../web/node_modules/@playwright/test');
const { readFileSync,mkdirSync } = require('node:fs');
const { resolve } = require('node:path');
const assert = require('node:assert/strict');
const { PrismaClient } = require('@prisma/client');
if(!process.env.DATABASE_URL?.includes('127.0.0.1:15439/identity_test'))throw new Error('仅允许专用本地测试库');
const credentials=JSON.parse(readFileSync(resolve(__dirname,'../private/service-test/local-admin.json'),'utf8'));
const db=new PrismaClient();
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const username=`gui-${Date.now()}`,name=`界面验证-${Date.now()}`;
  const artifacts=resolve(__dirname,'../private/gui');mkdirSync(artifacts,{recursive:true});
  try{
    await page.goto('http://127.0.0.1:4200/login');
    await page.getByLabel('登录账号',{exact:true}).fill('tab-check');
    await page.getByLabel('登录密码',{exact:true}).fill('tab-check-only');
    await page.getByRole('tab',{name:'禅道账号'}).click();
    assert.equal(await page.getByLabel('登录密码',{exact:true}).inputValue(),'');
    await page.getByRole('tab',{name:'账号密码'}).click();
    await page.locator('.el-loading-mask:visible,.el-overlay:visible,.el-message:visible').waitFor({state:'hidden'}).catch(()=>{});
    await page.screenshot({path:resolve(artifacts,'login-desktop.png'),fullPage:true});
    await page.getByLabel('登录账号',{exact:true}).fill(credentials.username);
    await page.getByLabel('登录密码',{exact:true}).fill(credentials.password);
    await page.getByRole('button',{name:'登 录',exact:true}).click();
    await page.getByRole('heading',{name:'工作台',exact:true}).waitFor();
    await page.getByText('接入应用',{exact:true}).waitFor();
    const layout=await page.evaluate(()=>({sidebar:document.querySelector('.app-sidebar').getBoundingClientRect().width,header:document.querySelector('.app-header').getBoundingClientRect().height,padding:getComputedStyle(document.querySelector('.primary-page')).paddingTop,title:getComputedStyle(document.querySelector('h1')).fontSize,shadow:getComputedStyle(document.querySelector('.app-content')).boxShadow}));
    assert.equal(layout.sidebar,256);assert.equal(layout.header,56);assert.equal(layout.padding,'24px');assert.equal(layout.title,'18px');assert.notEqual(layout.shadow,'none');
    await page.getByRole('button',{name:'收起导航',exact:true}).click();
    assert.equal(await page.locator('.app-sidebar').evaluate(e=>e.getBoundingClientRect().width),64);
    await page.getByRole('button',{name:'展开导航',exact:true}).click();
    await page.locator('.el-loading-mask:visible,.el-overlay:visible,.el-message:visible').waitFor({state:'hidden'}).catch(()=>{});
    await page.screenshot({path:resolve(artifacts,'overview-desktop.png'),fullPage:true});
    await page.getByRole('link',{name:'员工身份',exact:true}).click();
    await page.getByRole('button',{name:'创建身份',exact:true}).click();
    const dialog=page.getByRole('dialog');
    await dialog.getByLabel('姓名',{exact:true}).fill(name);
    await dialog.getByLabel('登录账号',{exact:true}).fill(username);
    await dialog.getByLabel('部门',{exact:true}).fill('界面验证');
    await dialog.getByLabel('初始密码',{exact:true}).fill('Only-local-gui-test!2026');
    await dialog.getByRole('button',{name:'保存',exact:true}).click();
    await dialog.waitFor({state:'hidden'});
    await page.getByRole('textbox',{name:'搜索员工'}).fill(name);
    const row=page.getByRole('row').filter({hasText:name});await row.waitFor();
    await row.getByRole('button',{name:'编辑',exact:true}).click();
    await page.getByRole('dialog').getByLabel('部门',{exact:true}).fill('验证完成');
    await page.getByRole('dialog').getByRole('button',{name:'保存',exact:true}).click();
    await page.getByRole('dialog').waitFor({state:'hidden'});
    await row.getByText('验证完成',{exact:true}).waitFor();
    await row.getByRole('link',{name:'应用授权',exact:true}).click();
    await page.getByRole('dialog',{name:'应用访问授权'}).waitFor();
    await page.getByRole('dialog').getByRole('button',{name:'保存授权',exact:true}).click();
    await page.getByRole('dialog').waitFor({state:'hidden'});
    await page.getByRole('row').filter({hasText:name}).getByText('中心自动同步').waitFor();
    await page.locator('.el-loading-mask:visible,.el-overlay:visible,.el-message:visible').waitFor({state:'hidden'}).catch(()=>{});
    await page.screenshot({path:resolve(artifacts,'applications-desktop.png'),fullPage:true});
    await page.getByRole('link',{name:'账号安全',exact:true}).click();
    await page.getByRole('button',{name:'绑定认证器',exact:true}).waitFor();
    await page.getByRole('button',{name:'绑定认证器',exact:true}).click();
    await page.getByRole('dialog',{name:'验证身份'}).waitFor();
    await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
    await page.locator('.el-loading-mask:visible,.el-overlay:visible,.el-message:visible').waitFor({state:'hidden'}).catch(()=>{});
    await page.screenshot({path:resolve(artifacts,'account-desktop.png'),fullPage:true});
    await page.getByRole('link',{name:'认证配置',exact:true}).click();
    await page.getByRole('heading',{name:'登录方式',exact:true}).waitFor();
    await page.locator('.el-loading-mask:visible,.el-overlay:visible,.el-message:visible').waitFor({state:'hidden'}).catch(()=>{});
    await page.screenshot({path:resolve(artifacts,'settings-desktop.png'),fullPage:true});
    await page.getByRole('tab',{name:'邮件设置',exact:true}).click();
    await page.getByText('SMTP 发信服务',{exact:true}).waitFor();
    await page.locator('.el-loading-mask:visible,.el-overlay:visible,.el-message:visible').waitFor({state:'hidden'}).catch(()=>{});
    await page.screenshot({path:resolve(artifacts,'mail-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4200/account');
    await page.getByRole('button',{name:'绑定认证器',exact:true}).waitFor();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);
    await page.locator('.el-loading-mask:visible,.el-overlay:visible,.el-message:visible').waitFor({state:'hidden'}).catch(()=>{});
    await page.screenshot({path:resolve(artifacts,'account-mobile.png'),fullPage:true});
    await page.getByRole('button',{name:'打开导航',exact:true}).click();
    await page.getByRole('link',{name:'员工身份',exact:true}).click();
    await page.getByRole('heading',{name:'员工身份',exact:true}).waitFor();
    assert.equal(await page.locator('.app-sidebar').evaluate(e=>e.classList.contains('is-mobile-open')),false);
    assert.deepEqual(errors,[]);
    console.log('GUI 实测通过：登录 Tab、管理员登录、建号、资料编辑、应用授权、账号安全和移动端布局');
  }finally{
    await browser.close();
    const user=await db.user.findUnique({where:{username}});
    if(user){await db.applicationUser.deleteMany({where:{userId:user.id}});await db.user.delete({where:{id:user.id}})}
    await db.$disconnect();
  }
})().catch(e=>{console.error(e.message);process.exitCode=1});
