import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {ResourceStore,parseSnapshot,type Snapshot} from '../server/store.ts';
import {createResourceServer} from '../server/http.ts';
import {UnifiedAuthError} from '../server/unified-client.ts';
function snapshot():Snapshot{return {schemaVersion:1,collectedAt:new Date().toISOString(),hostname:'fixture',system:'Linux test',cpuCount:2,loadAverage:[0,0,0],memoryTotal:4000,memoryAvailable:2000,diskTotal:8000,diskFree:5000,dockerAvailable:true,containers:[],services:[],desktopRelease:null,expertRelease:null}}
test('采集失败保留成功快照，刷新去重，元数据修改持久化且不接受目标地址',async()=>{const dir=await mkdtemp(join(tmpdir(),'resource-test-'));let failure=false,count=0;const store=new ResourceStore(dir,'unused',async()=>{count++;await new Promise(r=>setTimeout(r,10));if(failure)throw new Error('sensitive diagnostics');return snapshot()});try{await store.initialize(resolve('server/resources.json'));const id=store.resources[0].id;await Promise.all([store.refresh(id,'a'),store.refresh(id,'b')]);assert.equal(count,1);const old=store.state.observations[id].snapshot;failure=true;await store.refresh(id,'a');assert.deepEqual(store.state.observations[id].snapshot,old);assert.match(store.state.observations[id].error!,/SSH 采集失败/);assert.doesNotMatch(JSON.stringify(store.overview()),/sensitive|credential/);await store.update(id,{owner:'负责人',notes:'备注',tags:['生产','生产'],poolId:'production-business',host:'attacker'},'test');assert.equal(store.resources[0].host,'1.12.253.86');const restored=new ResourceStore(dir,'unused');await restored.initialize(resolve('server/resources.json'));assert.equal(restored.overview().resources[0].poolId,'production-business');assert.deepEqual(restored.state.metadata[id].tags,['生产']);await assert.rejects(store.update(id,{owner:'',notes:'',tags:[],poolId:'unknown'},'test'));}finally{await rm(dir,{recursive:true,force:true})}});
test('真实 HTTP API 强制统一认证 resource-manager 受众与 CSRF',async()=>{const dir=await mkdtemp(join(tmpdir(),'resource-auth-'));const store=new ResourceStore(dir,'unused',async()=>snapshot());await store.initialize(resolve('server/resources.json'));let audience='';const identity={async introspect(token:string,appId?:string){audience=appId||'';if(token!=='a'.repeat(43))throw new UnifiedAuthError(401,'无权限');return {sub:'test-user',csrfToken:'csrf-value'} as any}};const server=createResourceServer(store,identity);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const port=(server.address() as any).port,base=`http://127.0.0.1:${port}`,id=store.resources[0].id;try{assert.equal((await fetch(base+'/api/overview')).status,401);assert.equal((await fetch(base+'/api/overview',{headers:{Authorization:'Bearer '+'b'.repeat(43)}})).status,401);const headers={Authorization:'Bearer '+'a'.repeat(43)};assert.equal((await fetch(base+'/api/overview',{headers})).status,200);assert.equal(audience,'resource-manager');assert.equal((await fetch(base+`/api/resources/${id}/refresh`,{method:'POST',headers})).status,403);assert.equal((await fetch(base+`/api/resources/${id}/refresh`,{method:'POST',headers:{...headers,'X-CSRF-Token':'csrf-value'}})).status,200);assert.equal((await fetch(base+'/api/command',{method:'POST',headers:{...headers,'X-CSRF-Token':'csrf-value'}})).status,404);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true})}});
test('采集器拒绝畸形与过期指标',()=>{assert.equal(parseSnapshot(JSON.stringify(snapshot())).cpuCount,2);assert.throws(()=>parseSnapshot('{}'));assert.throws(()=>parseSnapshot(JSON.stringify({...snapshot(),collectedAt:'2020-01-01'})));assert.throws(()=>parseSnapshot(JSON.stringify({...snapshot(),memoryTotal:-1})));});
