import { mount, flushPromises, type VueWrapper } from '@vue/test-utils';
import ElementPlus, { ElMessage, ElMessageBox } from 'element-plus';
import { afterEach, describe, expect, it, vi } from 'vitest';
import TemplateSettings from '@/components/TemplateSettings.vue';
import { api } from '@/api/client';
vi.mock('@/api/client', () => ({ api: { getTemplates: vi.fn(), saveTemplates: vi.fn() } }));
const system: any = { id: 'system-a', name: '体系 A' };
const settings = () => ({ systemId: system.id, maxLevel: 3, revisionNo: 4, levels: [1, 2, 3, 4, 5, 6].map(level => ({
  level, revisionNo: 1, affectedCount: 2, modules: [{ moduleKey: 'portrait', displayOrder: 1, name: level + '级概述', researchQuestion: '说明', fields: [{ fieldId: 'definition', label: '定义', fieldType: 'long_text', requirement: 'optional' }] }],
})) });
afterEach(() => { vi.restoreAllMocks(); document.body.innerHTML = ''; });
describe('TemplateSettings', () => {
  it('删除既有字段和模块先确认，取消不变，保存提交保留历史标识的删除标记', async () => {
    const data: any = settings();
    data.levels[0].modules.push({ moduleKey: 'second', displayOrder: 2, name: '待删除模块', researchQuestion: '', active: true, fields: [{ fieldId: 'child', label: '随模块删除字段', fieldType: 'long_text', requirement: 'optional', active: true }] });
    vi.mocked(api.getTemplates).mockResolvedValue(data);
    vi.mocked(api.saveTemplates).mockResolvedValue(settings() as any);
    const confirm = vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const saveCalls = vi.mocked(api.saveTemplates).mock.calls.length;
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    await wrapper.get('[data-module-key="portrait"] input[aria-label="模块名称"]').setValue('保留未保存模块名称');
    await wrapper.get('[data-field-id="definition"] input[aria-label="填写说明"]').setValue('删除后也要保留的字段说明');
    confirm.mockRejectedValueOnce('cancel');
    await wrapper.get('[data-field-id="definition"] button[aria-label="删除字段"]').trigger('click');
    await flushPromises();
    expect(wrapper.find('[data-field-id="definition"]').exists()).toBe(true);
    await wrapper.get('[data-field-id="definition"] button[aria-label="删除字段"]').trigger('click');
    await flushPromises();
    const fieldPrompt = String(confirm.mock.calls.at(-1)![0]);
    expect(fieldPrompt).toContain('定义');
    expect(fieldPrompt).toContain('历史');
    expect(fieldPrompt).toContain('保存');
    expect(wrapper.find('[data-field-id="definition"]').exists()).toBe(false);
    expect(wrapper.get('.template-nav-tree').text()).not.toContain('定义');
    await wrapper.get('[data-module-key="second"] button[aria-label="删除模块"]').trigger('click');
    await flushPromises();
    const modulePrompt = String(confirm.mock.calls.at(-1)![0]);
    expect(modulePrompt).toContain('待删除模块');
    expect(modulePrompt).toContain('字段');
    expect(modulePrompt).toContain('历史');
    expect(modulePrompt).toContain('保存');
    expect(wrapper.find('[data-module-key="second"]').exists()).toBe(false);
    expect(wrapper.get('.template-deleted-trigger').text()).toMatch(/已删除.*2/);
    expect((wrapper.get('input[aria-label="模块名称"]').element as HTMLInputElement).value).toBe('保留未保存模块名称');
    expect(vi.mocked(api.saveTemplates).mock.calls.length).toBe(saveCalls);
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    const payload = vi.mocked(api.saveTemplates).mock.calls.at(-1)![1];
    const modules = payload.levels[0]!.modules;
    expect(modules.find(module => module.moduleKey === 'portrait')!.fields[0]).toMatchObject({ fieldId: 'definition', active: false, deleted: true, description: '删除后也要保留的字段说明' });
    expect(modules.find(module => module.moduleKey === 'second')).toMatchObject({ moduleKey: 'second', active: false, deleted: true, fields: [{ fieldId: 'child', active: true }] });
    expect(payload.levels[1]!.modules[0]!.fields[0]).not.toHaveProperty('deleted', true);
    wrapper.unmount();
  });

  it('删除本次新增模块和字段直接移除，不生成历史删除项或自动保存', async () => {
    vi.mocked(api.getTemplates).mockResolvedValue(settings() as any);
    vi.mocked(api.saveTemplates).mockResolvedValue(settings() as any);
    vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const saveCalls = vi.mocked(api.saveTemplates).mock.calls.length;
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    const quick = (text: string) => wrapper.get('.template-nav-actions').findAll('button').find(button => button.text() === text)!;
    await quick('新增字段').trigger('click');
    await flushPromises();
    const field = wrapper.findAll('[data-field-id]').at(-1)!;
    const newFieldId = field.attributes('data-field-id');
    await field.get('button[aria-label="删除字段"]').trigger('click');
    await flushPromises();
    expect(wrapper.findAll('[data-field-id]')).toHaveLength(1);
    await quick('新增模块').trigger('click');
    await flushPromises();
    const module = wrapper.findAll('[data-module-key]').at(-1)!;
    const newModuleKey = module.attributes('data-module-key');
    await quick('新增字段').trigger('click');
    await flushPromises();
    await module.get('button[aria-label="删除模块"]').trigger('click');
    await flushPromises();
    expect(wrapper.findAll('[data-module-key]')).toHaveLength(1);
    expect(wrapper.findAll('.deleted-template-item')).toHaveLength(0);
    expect(vi.mocked(api.saveTemplates).mock.calls.length).toBe(saveCalls);
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    const modules = vi.mocked(api.saveTemplates).mock.calls.at(-1)![1].levels[0]!.modules;
    expect(modules.some(item => item.moduleKey === newModuleKey)).toBe(false);
    expect(modules[0]!.fields.some(item => item.fieldId === newFieldId)).toBe(false);
    expect(modules[0]!.fields).toHaveLength(1);
    wrapper.unmount();
  });

  it('已删除模块和字段可恢复，父模块恢复不改变子字段原停用或删除状态', async () => {
    const data: any = settings();
    data.levels[0].modules.push({ moduleKey: 'second', displayOrder: 2, name: '可恢复模块', researchQuestion: '模块原说明', active: true, fields: [
      { fieldId: 'alive', label: '正常子字段', fieldType: 'long_text', requirement: 'optional', active: true },
      { fieldId: 'off', label: '停用子字段', fieldType: 'long_text', requirement: 'optional', active: false },
      { fieldId: 'removed', label: '以前删除子字段', fieldType: 'long_text', requirement: 'optional', active: false, deleted: true },
    ] });
    vi.mocked(api.getTemplates).mockResolvedValue(data);
    vi.mocked(api.saveTemplates).mockResolvedValue(settings() as any);
    vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    await wrapper.get('[data-field-id="definition"] input[aria-label="填写说明"]').setValue('恢复时保留输入');
    await wrapper.get('[data-field-id="definition"] button[aria-label="删除字段"]').trigger('click');
    await flushPromises();
    await wrapper.get('[data-module-key="second"] button[aria-label="删除模块"]').trigger('click');
    await flushPromises();
    await wrapper.get('.template-deleted-trigger').trigger('click');
    await flushPromises();
    const restoredModule = Array.from(document.body.querySelectorAll<HTMLElement>('.deleted-template-item')).find(item => item.textContent?.includes('可恢复模块') && item.querySelector('[aria-label="恢复模块"]'))!;
    restoredModule.querySelector<HTMLButtonElement>('[aria-label="恢复模块"]')!.click();
    await flushPromises();
    const module = wrapper.get('[data-module-key="second"]');
    expect(module.classes()).not.toContain('inactive');
    expect(module.get('[data-field-id="off"]').classes()).toContain('inactive');
    expect(module.get('[data-field-id="alive"]').classes()).not.toContain('inactive');
    expect(module.find('[data-field-id="removed"]').exists()).toBe(false);
    await wrapper.get('.template-deleted-trigger').trigger('click');
    await flushPromises();
    const restoredField = Array.from(document.body.querySelectorAll<HTMLElement>('.deleted-template-item')).find(item => item.textContent?.includes('定义') && item.querySelector('[aria-label="恢复字段"]'))!;
    restoredField.querySelector<HTMLButtonElement>('[aria-label="恢复字段"]')!.click();
    await flushPromises();
    expect(wrapper.get('[data-field-id="definition"]').classes()).not.toContain('inactive');
    expect((wrapper.get('[data-field-id="definition"] input[aria-label="填写说明"]').element as HTMLInputElement).value).toBe('恢复时保留输入');
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    const modules = vi.mocked(api.saveTemplates).mock.calls.at(-1)![1].levels[0]!.modules;
    expect(modules.find(item => item.moduleKey === 'second')).toMatchObject({ deleted: false, active: true, fields: [{ fieldId: 'alive', active: true }, { fieldId: 'off', active: false }, { fieldId: 'removed', deleted: true, active: false }] });
    expect(modules.find(item => item.moduleKey === 'portrait')!.fields[0]).toMatchObject({ fieldId: 'definition', deleted: false, active: true });
    wrapper.unmount();
  });

  it('最后一个有效模块不可删除，目录删除选中字段仍需确认且各级独立', async () => {
    const data: any = settings();
    data.levels[0].modules.push({ moduleKey: 'inactive', displayOrder: 2, name: '已停用模块', researchQuestion: '', active: false, fields: [] });
    vi.mocked(api.getTemplates).mockResolvedValue(data);
    const confirm = vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const warning = vi.spyOn(ElMessage, 'warning');
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    await wrapper.get('[data-module-key="portrait"] button[aria-label="删除模块"]').trigger('click');
    await flushPromises();
    expect(wrapper.find('[data-module-key="portrait"]').exists()).toBe(true);
    expect(warning).toHaveBeenCalled();
    expect(confirm).not.toHaveBeenCalled();
    await wrapper.findAll('.template-nav-label').find(node => node.attributes('data-nav-key') === JSON.stringify(['portrait', 'definition']))!.trigger('click');
    await flushPromises();
    await wrapper.get('button[aria-label="删除选中项"]').trigger('click');
    await flushPromises();
    expect(confirm).toHaveBeenCalledTimes(1);
    expect(wrapper.find('[data-field-id="definition"]').exists()).toBe(false);
    await wrapper.findAll('[role="tab"]').find(tab => tab.text() === '2 级模板')!.trigger('click');
    await flushPromises();
    expect(wrapper.find('[data-field-id="definition"]').exists()).toBe(true);
    await wrapper.findAll('[role="tab"]').find(tab => tab.text() === '1 级模板')!.trigger('click');
    await flushPromises();
    expect(wrapper.find('[data-field-id="definition"]').exists()).toBe(false);
    wrapper.unmount();
  });

  it('上下移和拖拽跳过已删除项，保留其标识及其他数据', async () => {
    const data: any = settings();
    data.levels[0].modules[0].fields.push(
      { fieldId: 'deleted-field', label: '历史字段', fieldType: 'long_text', requirement: 'optional', active: false, deleted: true, description: '保留历史填写说明' },
      { fieldId: 'extra', label: '第二字段', fieldType: 'long_text', requirement: 'optional' },
    );
    data.levels[0].modules.push(
      { moduleKey: 'deleted-module', displayOrder: 2, name: '历史模块', researchQuestion: '保留模块说明', active: false, deleted: true, fields: [] },
      { moduleKey: 'second', displayOrder: 3, name: '第二模块', researchQuestion: '', active: true, fields: [] },
    );
    vi.mocked(api.getTemplates).mockResolvedValue(data);
    vi.mocked(api.saveTemplates).mockResolvedValue(settings() as any);
    vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    expect(wrapper.get('.template-nav-tree').text()).not.toContain('历史');
    await wrapper.get('[data-module-key="portrait"] button[aria-label="模块下移"]').trigger('click');
    await wrapper.get('[data-field-id="definition"] button[aria-label="字段下移"]').trigger('click');
    await flushPromises();
    expect(wrapper.findAll('[data-module-key]').map(item => item.attributes('data-module-key'))).toEqual(['second', 'portrait']);
    expect(wrapper.findAll('[data-field-id]').map(item => item.attributes('data-field-id'))).toEqual(['extra', 'definition']);
    const tree = wrapper.findComponent({ name: 'ElTree' });
    const node = (module: string, field?: string) => (tree.vm as any).getNode(JSON.stringify([module, field ?? null]));
    tree.vm.$emit('node-drop', node('second'), node('portrait'), 'after', new Event('drop'));
    await flushPromises();
    tree.vm.$emit('node-drop', node('portrait', 'extra'), node('portrait', 'definition'), 'after', new Event('drop'));
    await flushPromises();
    expect(wrapper.findAll('[data-module-key]').map(item => item.attributes('data-module-key'))).toEqual(['portrait', 'second']);
    expect(wrapper.findAll('[data-field-id]').map(item => item.attributes('data-field-id'))).toEqual(['definition', 'extra']);
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    const modules = vi.mocked(api.saveTemplates).mock.calls.at(-1)![1].levels[0]!.modules;
    expect(modules.find(item => item.moduleKey === 'deleted-module')).toMatchObject({ deleted: true, active: false, researchQuestion: '保留模块说明' });
    expect(modules.find(item => item.moduleKey === 'portrait')!.fields.find(item => item.fieldId === 'deleted-field')).toMatchObject({ deleted: true, active: false, description: '保留历史填写说明' });
    wrapper.unmount();
  });

  it('预览不能删除或恢复，保存中按钮禁用且删除与恢复方法均拒绝变更', async () => {
    const data: any = settings();
    data.levels[0].modules.push({ moduleKey: 'second', displayOrder: 2, name: '第二模块', active: true, researchQuestion: '', fields: [] });
    data.levels[0].modules[0].fields.push({ fieldId: 'removed', label: '以前删除字段', fieldType: 'long_text', requirement: 'optional', active: false, deleted: true });
    vi.mocked(api.getTemplates).mockResolvedValue(data);
    let rejectSave!: (reason: Error) => void;
    vi.mocked(api.saveTemplates).mockImplementation(() => new Promise((_resolve, reject) => { rejectSave = reject; }));
    const confirm = vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    await wrapper.get('.template-deleted-trigger').trigger('click');
    await flushPromises();
    const restore = wrapper.findAllComponents({ name: 'ElButton' }).find(button => button.attributes('aria-label') === '恢复字段')!;
    const deleteModule = wrapper.get('[data-module-key="second"]').findAllComponents({ name: 'ElButton' }).find((button: VueWrapper) => button.attributes('aria-label') === '删除模块')!;
    await wrapper.get('[aria-label="预览模板"]').trigger('click');
    await flushPromises();
    expect(wrapper.find('button[aria-label="删除模块"]').exists()).toBe(false);
    expect(wrapper.find('button[aria-label="删除字段"]').exists()).toBe(false);
    deleteModule.vm.$emit('click', new MouseEvent('click'));
    restore.vm.$emit('click', new MouseEvent('click'));
    await flushPromises();
    expect(confirm).not.toHaveBeenCalled();
    expect(wrapper.find('[data-field-id="removed"]').exists()).toBe(false);
    expect(wrapper.find('[data-module-key="second"]').exists()).toBe(true);
    await wrapper.get('[aria-label="预览模板"]').trigger('click');
    await flushPromises();
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    expect(wrapper.get('[data-module-key="second"] button[aria-label="删除模块"]').attributes('disabled')).toBeDefined();
    expect(wrapper.get('[data-field-id="definition"] button[aria-label="删除字段"]').attributes('disabled')).toBeDefined();
    const confirmCount = confirm.mock.calls.length;
    wrapper.get('[data-module-key="second"]').findAllComponents({ name: 'ElButton' }).find((button: VueWrapper) => button.attributes('aria-label') === '删除模块')!.vm.$emit('click', new MouseEvent('click'));
    restore.vm.$emit('click', new MouseEvent('click'));
    await flushPromises();
    expect(confirm.mock.calls.length).toBe(confirmCount);
    expect(wrapper.find('[data-module-key="second"]').exists()).toBe(true);
    expect(wrapper.find('[data-field-id="removed"]').exists()).toBe(false);
    rejectSave(new Error('保存失败'));
    await flushPromises();
    expect(wrapper.emitted('close')).toBeUndefined();
    wrapper.unmount();
  });

  it('常驻新增字段入口跟随所选模块或字段，保留输入且不自动保存', async () => {
    const data = settings();
    data.levels[0]!.modules.push({ ...data.levels[0]!.modules[0]!, moduleKey: 'second', name: '第二模块', fields: [{ fieldId: 'definition', label: '第二模块定义', fieldType: 'long_text', requirement: 'optional' }] });
    vi.mocked(api.getTemplates).mockResolvedValue(data as any);
    const saveCalls = vi.mocked(api.saveTemplates).mock.calls.length;
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    const quickField = () => wrapper.get('.template-nav-actions').findAll('button').find(button => button.text() === '新增字段')!;
    const firstModule = wrapper.get('[data-module-key="portrait"]');
    const secondModule = wrapper.get('[data-module-key="second"]');
    await firstModule.get('input[aria-label="填写说明"]').setValue('需要保留的未保存说明');
    await wrapper.findAll('.template-nav-label').find(node => node.attributes('data-nav-key') === JSON.stringify(['second', null]))!.trigger('click');
    await flushPromises();
    expect(quickField().attributes('title')).toContain('第二模块');
    await quickField().trigger('click');
    await flushPromises();
    expect(firstModule.findAll('[data-field-id]')).toHaveLength(1);
    expect(secondModule.findAll('[data-field-id]')).toHaveLength(2);
    expect(document.activeElement).toBe(secondModule.findAll('input[aria-label="字段名称"]').at(-1)!.element);
    await wrapper.findAll('.template-nav-label').find(node => node.attributes('data-nav-key') === JSON.stringify(['second', 'definition']))!.trigger('click');
    await flushPromises();
    expect(quickField().attributes('title')).toContain('第二模块');
    await quickField().trigger('click');
    await flushPromises();
    expect(secondModule.findAll('[data-field-id]')).toHaveLength(3);
    expect((firstModule.get('input[aria-label="填写说明"]').element as HTMLInputElement).value).toBe('需要保留的未保存说明');
    expect(vi.mocked(api.saveTemplates).mock.calls.length).toBe(saveCalls);
    wrapper.unmount();
  });

  it('手动聚焦正文输入后，快捷新增字段跟随实际编辑的模块', async () => {
    const data = settings();
    data.levels[0]!.modules.push({ ...data.levels[0]!.modules[0]!, moduleKey: 'second', name: '第二模块', fields: [{ fieldId: 'definition', label: '第二模块定义', fieldType: 'long_text', requirement: 'optional' }] });
    vi.mocked(api.getTemplates).mockResolvedValue(data as any);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    const quickField = () => wrapper.get('.template-nav-actions').findAll('button').find(button => button.text() === '新增字段')!;
    await wrapper.findAll('.template-nav-label').find(node => node.attributes('data-nav-key') === JSON.stringify(['second', null]))!.trigger('click');
    await flushPromises();
    const firstModule = wrapper.get('[data-module-key="portrait"]');
    const secondModule = wrapper.get('[data-module-key="second"]');
    (firstModule.get('input[aria-label="填写说明"]').element as HTMLInputElement).focus();
    await flushPromises();
    expect(quickField().attributes('title')).toContain('1级概述');
    expect(wrapper.get('.template-nav-tree .is-current .template-nav-name').text()).toBe('定义');
    await quickField().trigger('click');
    await flushPromises();
    expect(firstModule.findAll('[data-field-id]')).toHaveLength(2);
    expect(secondModule.findAll('[data-field-id]')).toHaveLength(1);
    (secondModule.get('input[aria-label="模块名称"]').element as HTMLInputElement).focus();
    await secondModule.get('input[aria-label="模块名称"]').setValue('正文改名模块');
    await flushPromises();
    expect(quickField().attributes('title')).toContain('正文改名模块');
    await quickField().trigger('click');
    await flushPromises();
    expect(secondModule.findAll('[data-field-id]')).toHaveLength(2);
    expect(document.activeElement).toBe(secondModule.findAll('input[aria-label="字段名称"]').at(-1)!.element);
    wrapper.unmount();
  });

  it('空模板先新增模块再新增字段，各级新增内容彼此独立', async () => {
    const data = settings();
    data.levels[0]!.modules = [];
    vi.mocked(api.getTemplates).mockResolvedValue(data as any);
    const saveCalls = vi.mocked(api.saveTemplates).mock.calls.length;
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    const quick = (text: string) => wrapper.get('.template-nav-actions').findAll('button').find(button => button.text() === text)!;
    expect(quick('新增字段').attributes('disabled')).toBeDefined();
    await quick('新增字段').trigger('click');
    expect(wrapper.findAll('[data-module-key]')).toHaveLength(0);
    await quick('新增模块').trigger('click');
    await flushPromises();
    const firstModule = wrapper.get('[data-module-key]');
    const moduleKey = firstModule.attributes('data-module-key');
    expect(document.activeElement).toBe(firstModule.get('input[aria-label="模块名称"]').element);
    await firstModule.get('input[aria-label="模块名称"]').setValue('一级新模块');
    expect(quick('新增字段').attributes('disabled')).toBeUndefined();
    expect(quick('新增字段').attributes('title')).toContain('一级新模块');
    await quick('新增字段').trigger('click');
    await flushPromises();
    await firstModule.get('input[aria-label="字段名称"]').setValue('一级新字段');
    const fieldId = firstModule.get('[data-field-id]').attributes('data-field-id');
    await wrapper.findAll('[role="tab"]').find(tab => tab.text() === '2 级模板')!.trigger('click');
    await flushPromises();
    expect(quick('新增字段').attributes('title')).toContain('2级概述');
    await quick('新增字段').trigger('click');
    await flushPromises();
    expect(wrapper.findAll('[data-field-id]')).toHaveLength(2);
    await wrapper.findAll('[role="tab"]').find(tab => tab.text() === '1 级模板')!.trigger('click');
    await flushPromises();
    expect(wrapper.get('[data-module-key]').attributes('data-module-key')).toBe(moduleKey);
    expect(wrapper.get('[data-field-id]').attributes('data-field-id')).toBe(fieldId);
    expect((wrapper.get('input[aria-label="模块名称"]').element as HTMLInputElement).value).toBe('一级新模块');
    expect((wrapper.get('input[aria-label="字段名称"]').element as HTMLInputElement).value).toBe('一级新字段');
    expect(vi.mocked(api.saveTemplates).mock.calls.length).toBe(saveCalls);
    wrapper.unmount();
  });

  it('预览隐藏新增工具栏，保存中禁用快捷入口且方法拒绝重复新增', async () => {
    vi.mocked(api.getTemplates).mockResolvedValue(settings() as any);
    let rejectSave!: (reason: Error) => void;
    vi.mocked(api.saveTemplates).mockImplementation(() => new Promise((_resolve, reject) => { rejectSave = reject; }));
    vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    await wrapper.get('input[aria-label="模块名称"]').setValue('保存中保留名称');
    await wrapper.get('[aria-label="预览模板"]').trigger('click');
    await flushPromises();
    expect(wrapper.find('.template-nav-actions').exists()).toBe(false);
    await wrapper.get('[aria-label="预览模板"]').trigger('click');
    await flushPromises();
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    const actions = wrapper.get('.template-nav-actions');
    expect(actions.findAll('button').every(button => button.attributes('disabled') !== undefined)).toBe(true);
    for (const button of actions.findAllComponents({ name: 'ElButton' })) button.vm.$emit('click', new MouseEvent('click'));
    for (const button of wrapper.get('.template-editor-scroll').findAllComponents({ name: 'ElButton' }).filter((button: VueWrapper) => ['新增模块', '新增字段'].includes(button.text()))) button.vm.$emit('click', new MouseEvent('click'));
    await flushPromises();
    expect(wrapper.findAll('[data-module-key]')).toHaveLength(1);
    expect(wrapper.findAll('[data-field-id]')).toHaveLength(1);
    expect((wrapper.get('input[aria-label="模块名称"]').element as HTMLInputElement).value).toBe('保存中保留名称');
    rejectSave(new Error('保存失败，请重试'));
    await flushPromises();
    expect(actions.findAll('button').every(button => button.attributes('disabled') === undefined)).toBe(true);
    expect(wrapper.emitted('close')).toBeUndefined();
    wrapper.unmount();
  });

  it('目录仅允许同级前后拖拽，禁止嵌套、跨模块、混拖和预览拖拽', async () => {
    const data = settings();
    data.levels[0]!.modules[0]!.fields.push({ fieldId: 'extra', label: '第二字段', fieldType: 'long_text', requirement: 'optional' });
    data.levels[0]!.modules.push({ ...data.levels[0]!.modules[0]!, moduleKey: 'second', name: '第二模块' });
    vi.mocked(api.getTemplates).mockResolvedValue(data as any);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    const tree = wrapper.findComponent({ name: 'ElTree' });
    const node = (module: string, field?: string) => (tree.vm as any).getNode(JSON.stringify([module, field ?? null]));
    const allowDrop = tree.props('allowDrop') as (drag: unknown, target: unknown, type: string) => boolean;
    expect(tree.props('draggable')).toBe(true);
    expect(allowDrop(node('portrait'), node('second'), 'prev')).toBe(true);
    expect(allowDrop(node('portrait', 'definition'), node('portrait', 'extra'), 'next')).toBe(true);
    expect(allowDrop(node('portrait'), node('second'), 'inner')).toBe(false);
    expect(allowDrop(node('portrait', 'definition'), node('second', 'definition'), 'next')).toBe(false);
    expect(allowDrop(node('portrait'), node('portrait', 'definition'), 'prev')).toBe(false);
    expect(allowDrop(node('portrait'), node('portrait'), 'prev')).toBe(false);
    tree.vm.$emit('node-drop', node('portrait', 'definition'), node('second', 'definition'), 'after', new Event('drop'));
    await flushPromises();
    expect(wrapper.find('[data-module-key="portrait"] [data-field-id="definition"]').exists()).toBe(true);
    await wrapper.get('[aria-label="预览模板"]').trigger('click');
    await flushPromises();
    expect(tree.props('draggable')).toBe(false);
    expect(allowDrop(node('portrait'), node('second'), 'prev')).toBe(false);
    wrapper.unmount();
  });

  it('拖拽排序保留字段身份与内容，和上下移共用顺序且只在保存时提交', async () => {
    const data: any = settings();
    data.levels[0].modules[0].fields.push({ fieldId: 'extra', label: '第二字段', fieldType: 'enum', enumValues: ['选项 A'], requirement: 'optional', requiresEvidence: true });
    data.levels[0].modules.push({ ...data.levels[0].modules[0], moduleKey: 'second', name: '第二模块', fields: [] });
    vi.mocked(api.getTemplates).mockResolvedValue(data);
    let finishSave!: (value: any) => void;
    vi.mocked(api.saveTemplates).mockImplementation(() => new Promise(resolve => { finishSave = resolve; }));
    vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const saveCalls = vi.mocked(api.saveTemplates).mock.calls.length;
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    const tree = wrapper.findComponent({ name: 'ElTree' });
    const node = (module: string, field?: string) => (tree.vm as any).getNode(JSON.stringify([module, field ?? null]));
    await wrapper.get('[data-module-key="portrait"] input[aria-label="模块名称"]').setValue('未保存模块名');
    await wrapper.get('[data-field-id="definition"] input[aria-label="填写说明"]').setValue('未保存填写说明');
    tree.vm.$emit('node-drop', node('portrait'), node('second'), 'after', new Event('drop'));
    await flushPromises();
    expect(wrapper.findAll('[data-module-key]').map(module => module.attributes('data-module-key'))).toEqual(['second', 'portrait']);
    tree.vm.$emit('node-drop', node('portrait', 'definition'), node('portrait', 'extra'), 'after', new Event('drop'));
    await flushPromises();
    expect(wrapper.findAll('[data-module-key="portrait"] [data-field-id]').map(field => field.attributes('data-field-id'))).toEqual(['extra', 'definition']);
    expect((wrapper.get('[data-field-id="definition"] input[aria-label="填写说明"]').element as HTMLInputElement).value).toBe('未保存填写说明');
    await wrapper.get('[data-module-key="portrait"] button[aria-label="模块上移"]').trigger('click');
    await flushPromises();
    expect(wrapper.findAll('.template-nav-tree > .el-tree-node > .el-tree-node__content .template-nav-name').map(label => label.text())).toEqual(['未保存模块名', '第二模块']);
    expect(vi.mocked(api.saveTemplates).mock.calls.length).toBe(saveCalls);
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    expect(tree.props('draggable')).toBe(false);
    const allowDrop = tree.props('allowDrop') as (drag: unknown, target: unknown, type: string) => boolean;
    expect(allowDrop(node('portrait'), node('second'), 'next')).toBe(false);
    const payload = vi.mocked(api.saveTemplates).mock.calls.at(-1)![1];
    expect(payload.levels[0]!.modules.map(module => [module.moduleKey, module.displayOrder])).toEqual([['portrait', 1], ['second', 2]]);
    expect(payload.levels[0]!.modules[0]!.fields[0]).toMatchObject({ fieldId: 'extra', fieldType: 'enum', enumValues: ['选项 A'], requiresEvidence: true });
    expect(payload.levels[0]!.modules[0]!.fields[1]).toMatchObject({ fieldId: 'definition', description: '未保存填写说明' });
    finishSave(settings());
    await flushPromises();
    wrapper.unmount();
  });

  it('模块和字段目录使用复合标识定位，不丢失输入或触发保存', async () => {
    const data = settings();
    data.levels[0]!.modules.push({ ...data.levels[0]!.modules[0]!, moduleKey: 'second', name: '第二模块', fields: [{ fieldId: 'definition', label: '第二模块定义', fieldType: 'long_text', requirement: 'optional' }] });
    vi.mocked(api.getTemplates).mockResolvedValue(data as any);
    const saveCalls = vi.mocked(api.saveTemplates).mock.calls.length;
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    const firstModule = wrapper.get('[data-module-key="portrait"]');
    const secondModule = wrapper.get('[data-module-key="second"]');
    await firstModule.get('input[aria-label="字段名称"]').setValue('保留当前输入');
    const key = JSON.stringify(['second', 'definition']);
    await wrapper.findAll('.template-nav-label').find(node => node.attributes('data-nav-key') === key)!.trigger('click');
    await flushPromises();
    expect(document.activeElement).toBe(secondModule.get('[data-field-id="definition"]').element);
    expect(wrapper.get('.template-nav-tree .is-current .template-nav-name').text()).toBe('第二模块定义');
    expect((firstModule.get('input[aria-label="字段名称"]').element as HTMLInputElement).value).toBe('保留当前输入');
    expect(vi.mocked(api.saveTemplates).mock.calls.length).toBe(saveCalls);
    wrapper.unmount();
  });

  it('目录实时同步模块与字段改名、排序和停用状态', async () => {
    const data = settings();
    data.levels[0]!.modules[0]!.fields.push({ fieldId: 'extra', label: '第二字段', fieldType: 'long_text', requirement: 'optional' });
    data.levels[0]!.modules.push({ ...data.levels[0]!.modules[0]!, moduleKey: 'second', name: '第二模块', fields: [] });
    vi.mocked(api.getTemplates).mockResolvedValue(data as any);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    const module = wrapper.get('[data-module-key="portrait"]');
    await module.get('input[aria-label="模块名称"]').setValue('改名模块');
    await module.get('input[aria-label="字段名称"]').setValue('改名字段');
    expect(wrapper.get('.template-nav-tree').text()).toContain('改名模块');
    expect(wrapper.get('.template-nav-tree').text()).toContain('改名字段');
    await module.get('[data-field-id="definition"] button[aria-label="字段下移"]').trigger('click');
    await module.get('button[aria-label="模块下移"]').trigger('click');
    await flushPromises();
    expect(wrapper.findAll('.template-nav-name').map(node => node.text())).toEqual(['第二模块', '改名模块', '第二字段', '改名字段']);
    await module.get('[data-field-id="definition"] .el-switch').trigger('click');
    await flushPromises();
    const label = wrapper.findAll('.template-nav-label').find(node => node.attributes('data-nav-key') === JSON.stringify(['portrait', 'definition']))!;
    expect(label.classes()).toContain('is-inactive');
    expect(label.text()).toContain('停用');
    await module.get('.module-head .el-switch').trigger('click');
    await flushPromises();
    expect(wrapper.findAll('.template-nav-label.is-inactive')).toHaveLength(3);
    wrapper.unmount();
  });

  it('切换级别保留各级输入，预览目录与可见字段一致', async () => {
    const data: any = settings();
    data.levels[0].modules[0].fields.push({ fieldId: 'disabled', label: '停用字段', fieldType: 'long_text', requirement: 'optional', active: false });
    data.levels[0].modules.push({ moduleKey: 'inactive', name: '停用模块', active: false, displayOrder: 2, researchQuestion: '', fields: [] });
    vi.mocked(api.getTemplates).mockResolvedValue(data);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    await wrapper.get('input[aria-label="模块名称"]').setValue('一级未保存名称');
    await wrapper.findAll('[role="tab"]').find(tab => tab.text() === '2 级模板')!.trigger('click');
    await flushPromises();
    expect(wrapper.get('.template-nav-tree').text()).toContain('2级概述');
    expect(wrapper.get('.template-nav-tree').text()).not.toContain('一级未保存名称');
    await wrapper.get('input[aria-label="模块名称"]').setValue('二级独立名称');
    await wrapper.findAll('[role="tab"]').find(tab => tab.text() === '1 级模板')!.trigger('click');
    await wrapper.get('[aria-label="预览模板"]').trigger('click');
    await flushPromises();
    expect(wrapper.get('.template-nav-tree').text()).toContain('一级未保存名称');
    expect(wrapper.get('.template-nav-tree').text()).not.toContain('停用字段');
    expect(wrapper.get('.template-nav-tree').text()).not.toContain('停用模块');
    expect(wrapper.find('[data-field-id="disabled"]').exists()).toBe(false);
    expect(wrapper.find('[data-module-key="inactive"]').exists()).toBe(false);
    await wrapper.findAll('.template-nav-label').find(node => node.attributes('data-nav-key') === JSON.stringify(['portrait', 'definition']))!.trigger('click');
    await flushPromises();
    expect(document.activeElement).toBe(wrapper.get('[data-field-id="definition"]').element);
    await wrapper.get('[aria-label="预览模板"]').trigger('click');
    await flushPromises();
    expect((wrapper.get('input[aria-label="模块名称"]').element as HTMLInputElement).value).toBe('一级未保存名称');
    await wrapper.findAll('[role="tab"]').find(tab => tab.text() === '2 级模板')!.trigger('click');
    expect((wrapper.get('input[aria-label="模块名称"]').element as HTMLInputElement).value).toBe('二级独立名称');
    wrapper.unmount();
  });

  it('新增模块和字段自动选中并聚焦名称，窄屏目录点击后收起', async () => {
    vi.mocked(api.getTemplates).mockResolvedValue(settings() as any);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    await wrapper.get('.template-editor-scroll').findAll('button').find(button => button.text() === '新增模块')!.trigger('click');
    await flushPromises();
    const module = wrapper.findAll('[data-module-key]').at(-1)!;
    expect(document.activeElement).toBe(module.get('input[aria-label="模块名称"]').element);
    expect(wrapper.get('.template-nav-tree .is-current .template-nav-name').text()).toBe('新模块');
    await module.findAll('button').find(button => button.text() === '新增字段')!.trigger('click');
    await flushPromises();
    expect(document.activeElement).toBe(module.get('input[aria-label="字段名称"]').element);
    expect(wrapper.get('.template-nav-tree .is-current .template-nav-name').text()).toBe('新字段');
    await wrapper.get('button[aria-label="展开模板目录"]').trigger('click');
    expect(wrapper.get('.template-nav').classes()).toContain('is-mobile-open');
    await wrapper.findAll('.template-nav-label')[0]!.trigger('click');
    await flushPromises();
    expect(wrapper.get('.template-nav').classes()).not.toContain('is-mobile-open');
    expect(wrapper.get('button[aria-label="展开模板目录"]').attributes('aria-expanded')).toBe('false');
    wrapper.unmount();
  });

  it('按体系读取，编辑一级不污染二级，保存携带设置修订号', async () => {
    vi.mocked(api.getTemplates).mockResolvedValue(settings() as any);
    vi.mocked(api.saveTemplates).mockResolvedValue(settings() as any);
    vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    expect(api.getTemplates).toHaveBeenCalledWith('system-a');
    await wrapper.get('input[aria-label="模块名称"]').setValue('一级新名称');
    await wrapper.findAll('[role="tab"]').find(tab => tab.text() === '2 级模板')!.trigger('click');
    expect((wrapper.get('input[aria-label="模块名称"]').element as HTMLInputElement).value).toBe('2级概述');
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    const payload = vi.mocked(api.saveTemplates).mock.calls[0]![1];
    expect(payload.expectedRevisionNo).toBe(4);
    expect(payload.levels).toHaveLength(3);
    expect(payload.levels[0]!.modules[0]!.name).toBe('一级新名称');
    expect(payload.levels[1]!.modules[0]!.name).toBe('2级概述');
    expect(wrapper.emitted('saved')).toHaveLength(1); wrapper.unmount();
  });
  it('模板保存冲突时保留输入，不关闭设置', async () => {
    vi.mocked(api.getTemplates).mockResolvedValue(settings() as any);
    vi.mocked(api.saveTemplates).mockRejectedValue(new Error('模板设置已被修改'));
    vi.spyOn(ElMessageBox, 'confirm').mockResolvedValue('confirm' as never);
    const wrapper = mount(TemplateSettings, { props: { system }, global: { plugins: [ElementPlus] }, attachTo: document.body });
    await flushPromises();
    await wrapper.get('input[aria-label="模块名称"]').setValue('待核对内容');
    await wrapper.findAll('button').find(button => button.text() === '保存模板')!.trigger('click');
    await flushPromises();
    expect(wrapper.text()).toContain('模板设置已被修改');
    expect((wrapper.get('input[aria-label="模块名称"]').element as HTMLInputElement).value).toBe('待核对内容');
    expect(wrapper.emitted('close')).toBeUndefined(); wrapper.unmount();
  });
});
