import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, mkdir } from 'node:fs/promises';
import { parseEnv } from 'node:util';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { randomBytes } from 'node:crypto';
import { resolve } from 'node:path';
import { PrismaClient } from '@prisma/client';
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter } from '@nestjs/platform-fastify';
import {kernelFixture} from './kernel-fixture.mjs';

test('行政区划与组织机构：真实数据库、API、权限和事务保护', async t => {
  const kernel=await kernelFixture([{id:'identity',name:'统一身份'},{id:'scoped-app',name:'范围测试应用'},{id:'outside-app',name:'范围外应用'}]);t.after(kernel.close);
  const settings = parseEnv(await readFile(process.env.IDENTITY_TEST_ENV_FILE || new URL('../../mg-desktop-one/.runtime/local/identity.env',import.meta.url),'utf8'));
  const database = new URL(settings.DATABASE_URL);
  assert.equal(database.hostname,'127.0.0.1'); assert.equal(database.port,'15439'); assert.equal(database.pathname,'/identity_test');
  const schema = `identity_geography_${process.pid}_${Date.now()}`;
  assert.match(schema,/^identity_geography_\d+_\d+$/); database.searchParams.set('schema',schema);
  process.env.DATABASE_URL=database.href;
  const db=new PrismaClient(); let app, browser;
  t.after(async()=>{await browser?.close();await app?.close();await db.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await db.$disconnect();});
  execFileSync(process.execPath,['node_modules/prisma/build/index.js','db','push','--skip-generate'],{env:process.env,stdio:'pipe'});
  const [{AppModule},{hashPassword}] = await Promise.all([import('../dist/app.module.js'),import('../dist/password.js')]);
  app=await NestFactory.create(AppModule,new FastifyAdapter(),{logger:false});app.setGlobalPrefix('api');
  // 使用实际构建页面和真实 API 完成浏览器验证。
  const root=resolve(process.env.IDENTITY_TEST_WEB_DIR || 'web/dist');
  const {readFile:read}=await import('node:fs/promises');
  app.getHttpAdapter().getInstance().get('/*',async(req,reply)=>{
    const path=new URL(req.url,'http://local').pathname;
    if(path.startsWith('/api/'))return reply.code(404).send({message:'接口不存在'});
    const file=resolve(root,'.'+path);if(!file.startsWith(root))return reply.code(403).send();
    try{const body=await read(file);reply.type(path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.woff2')?'font/woff2':path.endsWith('.png')?'image/png':path.endsWith('.svg')?'image/svg+xml':'text/html');return reply.send(body);}catch{return reply.type('text/html').send(await read(resolve(root,'index.html')));}
  });
  await app.listen(0,'127.0.0.1');const origin=await app.getUrl();
  const password=randomBytes(24).toString('base64url'), passwordHash=await hashPassword(password);
  const admin=await db.user.create({data:{username:'geography-admin',displayName:'区划测试管理员',passwordHash}});
  const member=await db.user.create({data:{username:'geography-member',displayName:'区划测试成员',passwordHash}});
  const role=await db.role.create({data:{key:'platform-admin',name:'平台管理员'}});
  await db.userRole.create({data:{userId:admin.id,roleId:role.id}});
  await db.application.create({data:{clientId:'identity'}});
  await db.applicationUser.createMany({data:[admin,member].map(user=>({userId:user.id,clientId:'identity',enabled:true}))});
  async function login(username){const response=await fetch(origin+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password})});assert.equal(response.status,200);const data=await response.json();return {cookie:response.headers.getSetCookie().map(c=>c.split(';')[0]).join('; '),csrf:data.csrfToken};}
  const auth=await login(admin.username), ordinary=await login(member.username);
  async function call(path,body,method=body===undefined?'GET':'POST',status=200,session=auth){const response=await fetch(origin+'/api'+path,{method,headers:{'content-type':'application/json',cookie:session.cookie,'x-csrf-token':session.csrf},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();assert.equal(response.status,status,JSON.stringify(result));return result;}
  let province,city,county,zone,zone2,org;
  await t.test('管理身份、显式应用授权和 CSRF 均必需',async()=>{
    await call('/divisions',undefined,'GET',401,{cookie:'',csrf:''});await call('/organizations',undefined,'GET',403,ordinary);
    await call('/divisions',{name:'拒绝',code:'410000'},'POST',403,{...auth,csrf:''});
    await db.applicationUser.update({where:{clientId_userId:{clientId:'identity',userId:admin.id}},data:{enabled:false}});await call('/divisions',undefined,'GET',403);
    await db.applicationUser.update({where:{clientId_userId:{clientId:'identity',userId:admin.id}},data:{enabled:true}});
  });
  await t.test('层级自动计算、重复编码及未知字段拒绝',async()=>{
    province=await call('/divisions',{name:'测试省',code:'410000',type:'province'},'POST',201);
    city=await call('/divisions',{name:'测试市',code:'410100',type:'city',parentId:province.id},'POST',201);
    county=await call('/divisions',{name:'测试区',code:'410105',type:'district',parentId:city.id},'POST',201);assert.equal(county.level,3);
    await call('/divisions',{name:'重复编码',code:'410000'},'POST',409);
    await call('/divisions',{name:'非法参数',code:'420000',level:99},'POST',400);
    await call('/divisions/'+province.id,{parentId:county.id},'PATCH',409);
  });
  await t.test('功能区托管支持多对多，错误保存整体回滚',async()=>{
    await call('/divisions',{name:'错误功能区',code:'4101-BAD',type:'functional_zone',standard:true},'POST',400);
    zone=await call('/divisions',{name:'测试功能区',code:'4101-ZONE',type:'functional_zone',standard:false,parentId:city.id,officialIds:[county.id]},'POST',201);
    zone2=await call('/divisions',{name:'第二功能区',code:'4101-ZONE2',type:'functional_zone',standard:false,parentId:city.id,officialIds:[county.id,city.id]},'POST',201);
    assert.equal(await db.divisionMapping.count({where:{officialId:county.id}}),2);
    await call('/divisions/'+zone.id,{name:'不应保存',officialIds:[zone2.id]},'PATCH',409);assert.equal((await db.division.findUnique({where:{id:zone.id}})).name,'测试功能区');
    await call('/divisions/'+county.id,{standard:false},'PATCH',409);await call('/divisions/'+county.id,{},'DELETE',409);
  });
  await t.test('机构信用代码唯一、挂牌随主记录原子保存，局部更新保留挂牌',async()=>{
    org=await call('/organizations',{name:'测试机构',creditCode:'12410000MB1000001X',divisionId:county.id,plaques:['测试挂牌甲','测试挂牌乙']},'POST',201);
    await call('/organizations',{name:'重复主体',creditCode:org.creditCode,divisionId:city.id},'POST',409);
    await call('/organizations/'+org.id,{name:'不应保存',plaques:['相同','相同']},'PATCH',400);
    assert.equal((await db.organization.findUnique({where:{id:org.id}})).name,'测试机构');
    const renamed=await call('/organizations/'+org.id,{name:'测试机构新名称'},'PATCH');assert.equal(renamed.plaques.length,2);
    await call('/organizations/'+org.id,{enabled:'false'},'PATCH',400);
    await call('/organizations/'+org.id,{},'DELETE',409);
    await call('/divisions/'+county.id,{enabled:false},'PATCH',409);
  });
  await t.test('并发互相移动最多一个成功，层级和子节点同步',async()=>{
    const a=await call('/divisions',{name:'并发甲',code:'A1',standard:false},'POST',201),b=await call('/divisions',{name:'并发乙',code:'B1',standard:false},'POST',201);
    const move=(id,parentId)=>fetch(origin+'/api/divisions/'+id,{method:'PATCH',headers:{'content-type':'application/json',cookie:auth.cookie,'x-csrf-token':auth.csrf},body:JSON.stringify({parentId})});
    const results=await Promise.all([move(a.id,b.id),move(b.id,a.id)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);
    await call('/divisions/'+city.id,{parentId:null},'PATCH');assert.equal((await db.division.findUnique({where:{id:county.id}})).level,2);
    await call('/divisions/'+city.id,{parentId:province.id},'PATCH');assert.equal((await db.division.findUnique({where:{id:county.id}})).level,3);
  });
  await t.test('用户机构关联、默认角色与范围应用授权边界',async()=>{
    const {ensurePlatformAdministratorRole}=await import('../dist/platform-role.js');
    await ensurePlatformAdministratorRole(db);await ensurePlatformAdministratorRole(db);
    assert.equal(await db.role.count({where:{key:{in:['division-admin','organization-admin']}}}),2);
    const divisionRole=await db.role.findUniqueOrThrow({where:{key:'division-admin'}}),organizationRole=await db.role.findUniqueOrThrow({where:{key:'organization-admin'}});
    const scopedAdmin=await db.user.create({data:{username:'scope-admin',displayName:'范围测试管理员',passwordHash}});
    await db.userRole.createMany({data:[divisionRole,organizationRole].map(r=>({userId:scopedAdmin.id,roleId:r.id}))});
    await db.applicationUser.create({data:{userId:scopedAdmin.id,clientId:'identity',enabled:true}});
    const scopedAuth=await login(scopedAdmin.username);
    await db.application.createMany({data:[{clientId:'scoped-app'},{clientId:'outside-app'}]});
    const other=await call('/organizations',{name:'第二测试机构',creditCode:'12410000MB1000009X',divisionId:city.id},'POST',201);
    const beforeRoles=await db.userRole.findMany({where:{userId:member.id}}), beforeGrants=await db.applicationUser.findMany({where:{userId:member.id}});
    const associate=(organizations,status=200,session=auth)=>call(`/users/${member.id}/organizations`,{organizations},'PUT',status,session);
    await associate([{organizationId:org.id,isPrimary:true},{organizationId:other.id,isPrimary:true}],400);
    await associate([{organizationId:org.id,isPrimary:true},{organizationId:org.id,isPrimary:false}],400);
    await associate([{organizationId:'missing',isPrimary:true}],409);
    await associate([{organizationId:org.id,isPrimary:true}],403,scopedAuth);
    await associate([{organizationId:org.id,isPrimary:true}],403,{...auth,csrf:''});
    await associate([{organizationId:org.id,isPrimary:true},{organizationId:other.id,isPrimary:false}]);
    assert.deepEqual(await db.userRole.findMany({where:{userId:member.id}}),beforeRoles);
    assert.deepEqual(await db.applicationUser.findMany({where:{userId:member.id}}),beforeGrants);
    const listed=(await call('/users')).find(u=>u.id===member.id);assert.equal(listed.organizations.length,2);assert.equal(listed.organizations.filter(o=>o.isPrimary).length,1);
    await call('/organizations/'+org.id,{enabled:false},'PATCH');await call('/organizations/'+org.id,{},'DELETE',409);
    await associate([]);await associate([{organizationId:org.id,isPrimary:true}],409);
    await call('/organizations/'+org.id,{enabled:true},'PATCH');await associate([{organizationId:org.id,isPrimary:true}]);
    const configure=(kind,id,clientIds,administratorIds=[scopedAdmin.id],status=200,session=auth)=>call(`/scopes/${kind}/${id}`,{clientIds,administratorIds},'PUT',status,session);
    await configure('organization',org.id,['scoped-app'],[member.id],409);
    const orgScope=await configure('organization',org.id,['scoped-app']);
    const divisionScope=await configure('division',province.id,['scoped-app']);
    const otherScope=await configure('organization',other.id,['scoped-app'],[]);
    const grant=(scope,clientId,userId,enabled=true,status=200,session=scopedAuth)=>call(`/scopes/${scope.id}/applications/${clientId}/users/${userId}`,{enabled},'PUT',status,session);
    await configure('organization',org.id,['outside-app'],[scopedAdmin.id],403,scopedAuth);
    await call('/applications/scoped-app/users/'+member.id,{enabled:true},'PUT',403,scopedAuth);
    await call('/roles/users/'+member.id,{roleIds:[role.id]},'PUT',403,scopedAuth);
    await call(`/roles/${organizationRole.id}/applications/scoped-app`,{enabled:true},'PUT',409);
    await call(`/roles/${divisionRole.id}`,{},'DELETE',409);
    await call(`/roles/${organizationRole.id}`,{name:'越权更名'},'PATCH',409);
    await grant(otherScope,'scoped-app',member.id,true,403);
    await grant(orgScope,'outside-app',member.id,true,409);
    await grant(orgScope,'scoped-app',admin.id,true,409);
    await grant(orgScope,'scoped-app',member.id,true,403,{...scopedAuth,csrf:''});
    await grant(orgScope,'scoped-app',member.id);await grant(divisionScope,'scoped-app',member.id);
    const access=async()=> (await call(`/applications/users/${member.id}`)).find(a=>a.clientId==='scoped-app');
    assert.equal((await access()).sources.filter(s=>s.type==='scope').length,2);
    assert.equal((await call(`/scopes/${divisionScope.id}/members`,undefined,'GET',200,scopedAuth)).length,1);
    assert.equal((await call('/scopes',undefined,'GET',200,scopedAuth)).length,2);
    await configure('organization',org.id,[]);assert.equal((await access()).effective,true);
    assert.equal(await db.scopeGrant.count({where:{scopeId:orgScope.id}}),0);
    await configure('division',province.id,[]);assert.equal((await access()).effective,false);
    await configure('organization',org.id,['scoped-app']);await grant(orgScope,'scoped-app',member.id);
    await db.userRole.delete({where:{userId_roleId:{userId:scopedAdmin.id,roleId:organizationRole.id}}});
    await grant(orgScope,'scoped-app',member.id,false,403);
    await db.userRole.create({data:{userId:scopedAdmin.id,roleId:organizationRole.id}});
    await associate([]);assert.equal((await access()).effective,false);assert.equal(await db.scopeGrant.count({where:{userId:member.id}}),0);
    await associate([{organizationId:org.id,isPrimary:true}]);assert.equal((await access()).effective,false);
    await grant(orgScope,'scoped-app',member.id);
    await call('/organizations/'+org.id,{enabled:false},'PATCH');assert.equal((await access()).effective,false);
    await grant(orgScope,'scoped-app',member.id,false,403);
    await call('/organizations/'+org.id,{enabled:true},'PATCH');
    await call('/applications/scoped-app/users/'+member.id,{enabled:true},'PUT');
    await configure('organization',org.id,[]);assert.equal((await access()).effective,true);
    await call('/applications/scoped-app/users/'+member.id,{enabled:false},'PUT');
    assert.equal((await access()).effective,false);
    assert(await db.auditLog.count({where:{action:'scope.application'}}));assert(await db.auditLog.count({where:{action:'user.organizations'}}));
    if(process.env.GEOGRAPHY_GUI==='1'){
      const {chromium}=await import(process.env.IDENTITY_TEST_PLAYWRIGHT || '../web/node_modules/playwright-core/index.mjs');browser=await chromium.launch({channel:'chrome',headless:true});
      const context=await browser.newContext({viewport:{width:1440,height:960}});
      await context.addCookies(auth.cookie.split('; ').map(pair=>{const split=pair.indexOf('=');return {name:pair.slice(0,split),value:pair.slice(split+1),url:origin};}));
      const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
      await page.goto(origin+'/admin');await page.getByRole('heading',{name:'员工身份',exact:true}).waitFor();
      const row=page.getByRole('row',{name:/区划测试成员/});await row.getByRole('button',{name:'所属机构',exact:true}).click();
      const dialog=page.getByRole('dialog');await dialog.getByRole('combobox',{name:'所属组织机构',exact:true}).press('Enter');
      await page.getByRole('option',{name:'第二测试机构',exact:true}).click();await dialog.getByRole('combobox',{name:'所属组织机构',exact:true}).press('Escape');
      await dialog.getByRole('button',{name:'保存机构'}).click();await dialog.waitFor({state:'hidden'});
      await row.locator('td').filter({hasText:'第二测试机构'}).first().locator('.cell > div').filter({hasText:'第二测试机构'}).waitFor();
      await page.goto(origin+`/scopes?kind=organization&id=${org.id}`);await page.getByRole('combobox',{name:'可配置应用',exact:true}).press('Enter');
      await page.getByRole('option',{name:'范围测试应用',exact:true}).click();await page.getByRole('combobox',{name:'可配置应用',exact:true}).press('Escape');
      await page.getByRole('button',{name:'保存范围配置',exact:true}).click();await page.locator('.el-switch').filter({has:page.getByRole('switch',{name:'区划测试成员 范围测试应用',exact:true})}).waitFor();
      const out=resolve('.runtime/geography-verification');await mkdir(out,{recursive:true});await page.screenshot({path:resolve(out,'scopes-platform.png')});
      await context.clearCookies();await context.addCookies(scopedAuth.cookie.split('; ').map(pair=>{const split=pair.indexOf('=');return {name:pair.slice(0,split),value:pair.slice(split+1),url:origin};}));
      const loaded=page.waitForResponse(r=>r.url()===origin+'/api/scopes' && r.request().method()==='GET');
      await page.goto(origin+'/');await page.waitForURL('**/scopes');const response=await loaded;assert.equal(response.status(),200);await response.finished();
      await page.getByRole('combobox',{name:'管理范围',exact:true}).locator('xpath=ancestor::div[contains(@class,"el-select")][1]').click();await page.getByRole('option',{name:'组织机构 · 测试机构新名称',exact:true}).click();
      const toggle=page.locator('.el-switch').filter({has:page.getByRole('switch',{name:'区划测试成员 范围测试应用',exact:true})});await toggle.click();
      await page.waitForFunction(()=>document.querySelector('[role="switch"][aria-label="区划测试成员 范围测试应用"]')?.getAttribute('aria-checked')==='true');
      assert.equal((await access()).effective,true);assert.equal(await page.getByRole('button',{name:'保存范围配置'}).count(),0);
      await page.screenshot({path:resolve(out,'scopes-admin.png')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(out,'scopes-mobile.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
      assert.deepEqual(errors,[]);await context.close();await browser.close();browser=undefined;
    }
    await associate([]);assert(await db.user.findUnique({where:{id:member.id}}));
    await call('/organizations/'+other.id,{enabled:false},'PATCH');await call('/organizations/'+other.id,{},'DELETE');
  });
  if(process.env.GEOGRAPHY_GUI==='1')await t.test('真实浏览器新增编辑、树搜索、挂牌搜索及窄屏截图',async()=>{
    await browser?.close();
    const {chromium}=await import(process.env.IDENTITY_TEST_PLAYWRIGHT || '../web/node_modules/playwright-core/index.mjs');browser=await chromium.launch({channel:'chrome',headless:true});
    const context=await browser.newContext({viewport:{width:1440,height:960}});
    await context.addCookies(auth.cookie.split('; ').map(pair=>{const split=pair.indexOf('=');return {name:pair.slice(0,split),value:pair.slice(split+1),url:origin};}));
    const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(origin+'/divisions');await page.getByRole('heading',{name:'行政区划管理',exact:true}).waitFor();
    await page.getByRole('textbox',{name:'搜索区划',exact:true}).fill('测试区');await page.getByText('测试区',{exact:true}).waitFor();await page.getByText('测试省',{exact:true}).waitFor();
    await page.getByRole('button',{name:'新增区划',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('textbox',{name:'区划名称',exact:true}).fill('浏览器测试省');await dialog.getByRole('textbox',{name:'区划编码',exact:true}).fill('420000');await dialog.getByRole('button',{name:'保存',exact:true}).click();await dialog.waitFor({state:'hidden'});
    await page.getByRole('textbox',{name:'搜索区划',exact:true}).fill('浏览器测试省');await page.getByRole('cell',{name:'浏览器测试省',exact:true}).waitFor();
    await page.getByRole('button',{name:'编辑',exact:true}).click();await dialog.getByRole('textbox',{name:'区划名称',exact:true}).fill('浏览器测试省更新');await dialog.getByRole('button',{name:'保存',exact:true}).click();await dialog.waitFor({state:'hidden'});
    await page.getByRole('textbox',{name:'搜索区划',exact:true}).fill('测试');
    const out=resolve('.runtime/geography-verification');await mkdir(out,{recursive:true});await page.screenshot({path:resolve(out,'divisions-desktop.png')});
    await page.goto(origin+'/organizations');await page.getByRole('heading',{name:'组织机构管理',exact:true}).waitFor();
    await page.getByRole('textbox',{name:'搜索机构',exact:true}).fill('测试挂牌乙');await page.getByRole('row',{name:/测试机构新名称/}).waitFor();
    await page.getByRole('button',{name:'新增机构',exact:true}).click();await dialog.getByRole('textbox',{name:'机构主名称',exact:true}).fill('浏览器机构');await dialog.getByRole('textbox',{name:'统一社会信用代码',exact:true}).fill('12410000MB1000002X');
    await dialog.getByRole('combobox',{name:'所属区划',exact:true}).press('Enter');await page.getByRole('treeitem',{name:'测试省（410000）',exact:true}).click();
    await dialog.getByRole('button',{name:'添加挂牌',exact:true}).click();await dialog.getByRole('textbox',{name:'挂牌名称1',exact:true}).fill('浏览器挂牌');await dialog.getByRole('button',{name:'保存',exact:true}).click();await dialog.waitFor({state:'hidden'});
    await page.getByRole('textbox',{name:'搜索机构',exact:true}).fill('浏览器挂牌');await page.getByRole('row',{name:/浏览器机构/}).waitFor();
    await page.screenshot({path:resolve(out,'organizations-desktop.png')});
    for(const path of ['organizations','divisions']) {await page.goto(origin+'/'+path);await page.setViewportSize({width:390,height:844});await page.getByRole('heading',{level:1}).waitFor();await page.locator('.el-loading-mask').waitFor({state:'detached'});await page.screenshot({path:resolve(out,path+'-mobile.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
    assert.deepEqual(errors,[]);await context.close();
  });
  await t.test('删除与启停保护及审计记录',async()=>{
    await call('/organizations/'+org.id,{enabled:false},'PATCH');await call('/organizations/'+org.id,{},'DELETE');assert.equal(await db.organizationPlaque.count({where:{organizationId:org.id}}),0);
    await call('/divisions/'+zone.id,{},'DELETE');await call('/divisions/'+zone2.id,{},'DELETE');
    await call('/divisions/'+county.id,{enabled:false},'PATCH');await call('/organizations',{name:'不应创建',creditCode:'12410000MB1000003X',divisionId:county.id},'POST',409);
    await call('/divisions/'+county.id,{},'DELETE');assert(await db.auditLog.count({where:{action:'organization.deleted'}}));assert(await db.auditLog.count({where:{action:'division.updated'}}));
  });
});
