<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {ConfiguredApplicationShell,PageFrame,PageHeading,ContentPanel,serviceInvocationUrl,compareServiceVersions,compareContractVersions,type ServiceContract,type ServiceManifest} from '@mg-inside/frontend';
import {ElMessage,ElMessageBox} from 'element-plus';
import {application} from './main';
import ContractOperation from './ContractOperation.vue';
import {client,desktop} from './api';
interface Binding {environment:string;endpointRef:string;deploymentId:string;deploymentDigest:string;manifestDigest:string;contractDigest:string}
interface Lifecycle {status:'draft'|'published'|'deprecated'|'retired';revision:number;reason:string;at:string;actor:string;retireAfter?:string}
interface Deployment {endpointRef:string;name:string;appId:string;providerAppId:string;environment:string;baseUrl:string;deploymentId:string;artifactDigest:string;resourceRef:string;deployedAt:string;digest:string;services:Array<{serviceId:string;version:string;manifestDigest:string;contractDigest:string}>}
interface Publication {contract?:ServiceContract;contractDigest?:string;manifest:ServiceManifest;digest:string;at:string;actor:string;active:boolean;activeRevision:number;activeVersion:string|null;binding?:Binding;lifecycle?:Lifecycle}
interface Data {items:Publication[];canManage:boolean;storage?:{backend:string;environment:string};runningEnvironment?:string;bindingRequired?:boolean;environments?:Array<{id:string;name:string}>;deployments?:Deployment[];activity:Array<{id:string;at:string;serviceId:string;operationId:string;status:number;durationMs:number}>;audit:Array<{id:string;at:string;action:string;serviceId:string;version:string;binding?:Binding;previousBinding?:Binding;lifecycle?:Lifecycle;previousLifecycle?:Lifecycle}>}
const route=useRoute(),router=useRouter(),data=ref<Data|null>(null),loading=ref(false),error=ref(''),search=ref(''),selected=ref<Publication|null>(null),draft=ref(''),busy=ref(false);
const contractDraft=ref('');
const selectedEnvironment=ref(''),publishTarget=ref<Publication|null>(null),endpointChoice=ref(''),initialEndpoint=ref('');
const lifecycleLabels={draft:'草稿',published:'已发布',deprecated:'已弃用',retired:'已退役'};
const lifecycleTarget=ref<Publication|null>(null),lifecycleStatus=ref<Lifecycle['status']>('deprecated'),lifecycleReason=ref(''),retireAfter=ref(''),initialLifecycle=ref('');
const lifecycleDraft=()=>JSON.stringify([lifecycleStatus.value,lifecycleReason.value,retireAfter.value]);
const lifecycleDirty=computed(()=>!!lifecycleTarget.value&&lifecycleDraft()!==initialLifecycle.value);
const lifecycleChoices=computed(()=>lifecycleTarget.value?.lifecycle?.status==='draft'?['retired']:lifecycleTarget.value?.lifecycle?.status==='deprecated'?['deprecated','published','retired']:['deprecated']);
function editLifecycle(p:Publication){if(!p.lifecycle||p.lifecycle.status==='retired')return;lifecycleTarget.value=p;lifecycleStatus.value=p.lifecycle.status==='draft'?'retired':'deprecated';lifecycleReason.value=p.lifecycle.status==='deprecated'?p.lifecycle.reason:'';retireAfter.value=p.lifecycle.retireAfter||'';initialLifecycle.value=lifecycleDraft();}
async function closeLifecycle(done?:()=>void){if(busy.value)return;if(lifecycleDirty.value&&!await canLeave())return;lifecycleTarget.value=null;done?.()}
async function saveLifecycle(){
 const p=lifecycleTarget.value;if(!p?.lifecycle||busy.value||!lifecycleReason.value.trim())return;
 try{
  await ElMessageBox.confirm(`将 ${p.manifest.name} ${p.manifest.version} 标记为${lifecycleLabels[lifecycleStatus.value]}，此变更对所有环境生效。${lifecycleStatus.value==='retired'?'后台会检查所有环境均已停止使用，退役后不能恢复或重新发布。':lifecycleStatus.value==='deprecated'?'现有调用继续运行，新增或更换环境绑定将被拒绝。':'恢复后可再次选择该版本发布。'}`,'确认生命周期变更',{confirmButtonText:'确认变更',cancelButtonText:'取消',type:'warning'});
  busy.value=true;await client.request('/lifecycle'+environmentQuery(),{method:'POST',body:JSON.stringify({serviceId:p.manifest.serviceId,version:p.manifest.version,status:lifecycleStatus.value,reason:lifecycleReason.value.trim(),expectedRevision:p.lifecycle.revision,...(lifecycleStatus.value==='deprecated'&&retireAfter.value?{retireAfter:retireAfter.value}:{})})});
  lifecycleTarget.value=null;selected.value=null;await load();ElMessage.success('版本生命周期已更新');
 }catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{busy.value=false}
}
const endpointOptions=computed(()=>data.value?.deployments?.filter(d=>d.services.some(s=>s.serviceId===publishTarget.value?.manifest.serviceId&&s.version===publishTarget.value?.manifest.version&&s.manifestDigest===publishTarget.value?.digest&&s.contractDigest===publishTarget.value?.contractDigest))||[]);
const chosenDeployment=computed(()=>endpointOptions.value.find(d=>d.endpointRef===endpointChoice.value));
const environmentQuery=()=>selectedEnvironment.value?'?environment='+encodeURIComponent(selectedEnvironment.value):'';
const importInput=ref<HTMLInputElement|null>(null);
async function importRegistration(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(file.size>600*1024)throw new Error('登记包不能超过 600 KiB');if(dirty.value&&!await canLeave())return;busy.value=true;const value=JSON.parse(await file.text());if(!value?.manifest||!value?.contract||Object.keys(value).some(key=>!['manifest','contract'].includes(key)))throw new Error('登记包须包含 manifest 与 contract');draft.value=JSON.stringify(value.manifest,null,2);contractDraft.value=JSON.stringify(value.contract,null,2);ElMessage.success('登记包已导入，请核对后提交')}catch(e){ElMessage.error((e as Error).message)}finally{busy.value=false;input.value=''}}
const dirty=computed(()=>!!draft.value.trim()||!!contractDraft.value.trim()||!!publishTarget.value&&endpointChoice.value!==initialEndpoint.value||lifecycleDirty.value);
const page=computed(()=>application.pages.find(p=>p.path===route.path)||application.pages[0]);
const items=computed(()=>data.value?.items.filter(p=>[p.manifest.name,p.manifest.appId,p.manifest.description].join(' ').toLowerCase().includes(search.value.toLowerCase()))||[]);
const provider=ref(''),pageNumber=ref(1),pageSize=20;
const checking=ref(''),checkResult=ref(''),checked=ref('');
let checkRun=0;
const comparisonBase=ref('');
const versions=computed(()=>data.value?.items.filter(p=>p.manifest.serviceId===selected.value?.manifest.serviceId)||[]);
const baseline=computed(()=>comparisonBase.value?versions.value.find(p=>p.manifest.version===comparisonBase.value):versions.value.find(p=>p.active));
const changes=computed(()=>selected.value?compareServiceVersions(baseline.value?.manifest,selected.value.manifest):[]);
const contractChanges=computed(()=>selected.value?compareContractVersions(baseline.value?.contract,selected.value.contract,selected.value.manifest):[]);
watch(selected,()=>{checkRun++;checking.value='';checked.value='';checkResult.value='';comparisonBase.value=''});
async function check(p:Publication,op:ServiceManifest['operations'][number]){const run=++checkRun;checking.value=op.operationId;checked.value=op.operationId;checkResult.value='';try{await client.invoke(p.manifest.serviceId,op.operationId);if(run===checkRun)checkResult.value='调用成功，提供方已返回响应；可在调用记录中查看。'}catch(e){if(run===checkRun)checkResult.value=(e as Error).message}finally{if(run===checkRun)checking.value=''}}
const filtered=computed(()=>items.value.filter(p=>!provider.value||p.manifest.appId===provider.value));
const paged=computed(()=>filtered.value.slice((pageNumber.value-1)*pageSize,pageNumber.value*pageSize));
const providers=computed(()=>[...new Set(data.value?.items.map(p=>p.manifest.appId)||[])]);
watch([search,provider],()=>pageNumber.value=1);
const serviceCount=computed(()=>new Set(data.value?.items.map(p=>p.manifest.serviceId)).size);
const environmentLabel=computed(()=>({production:'生产',testing:'测试',development:'开发',local:'本地'} as Record<string,string>)[data.value?.storage?.environment||'']||data.value?.storage?.environment);
let loadRun=0,loadController:AbortController|undefined;
async function load(){const run=++loadRun;loadController?.abort();loadController=new AbortController();loading.value=true;error.value='';try{const result=await client.request<Data>(environmentQuery(),{signal:loadController.signal});if(run===loadRun){data.value=result;selectedEnvironment.value=result.storage?.environment||''}}catch(e){if(run===loadRun&&(e as Error).name!=='AbortError')error.value=(e as Error).message}finally{if(run===loadRun)loading.value=false}}
async function canLeave(){if(busy.value)return false;if(!dirty.value)return true;return ElMessageBox.confirm('有尚未提交的服务更改，确定放弃吗？','未提交更改',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'}).then(()=>{draft.value='';contractDraft.value='';publishTarget.value=null;lifecycleTarget.value=null;return true}).catch(()=>false)}
async function switchEnvironment(value:string){if(value===selectedEnvironment.value||!await canLeave())return;selectedEnvironment.value=value;selected.value=null;publishTarget.value=null;data.value=null;await load()}
async function closePublish(done?:()=>void){if(busy.value)return;if(endpointChoice.value!==initialEndpoint.value&&!await canLeave())return;publishTarget.value=null;done?.()}
desktop.configure({onClose:canLeave,onNavigate:async path=>{await router.push(path)}});
const removeGuard=router.beforeEach(async(to,from)=>to.path===from.path||await canLeave());
const beforeUnload=(event:BeforeUnloadEvent)=>{if(dirty.value||busy.value){event.preventDefault();event.returnValue=''}};
window.addEventListener('beforeunload',beforeUnload);
onUnmounted(()=>{loadRun++;loadController?.abort();removeGuard();window.removeEventListener('beforeunload',beforeUnload)});
watch([dirty,busy],()=>desktop.setState({dirty:dirty.value,busy:busy.value}));
async function navigate(path:string){if(path!==route.path&&await canLeave())await router.push(path)}
async function publish(){busy.value=true;desktop.setState({busy:true,dirty:true});try{let input;try{input=JSON.parse(draft.value)}catch{throw new Error('请输入合法 JSON 服务清单')};let contract;try{contract=contractDraft.value.trim()?JSON.parse(contractDraft.value):undefined}catch{throw new Error('请输入合法 JSON OpenAPI 契约')};await client.request('/publications'+environmentQuery(),{method:'POST',body:JSON.stringify({manifest:input,...(contractDraft.value.trim()?{contract}: {})})});draft.value='';contractDraft.value='';ElMessage.success('服务版本已登记，请在目录中启用');await load();busy.value=false;await router.push('/services')}catch(e){ElMessage.error((e as Error).message)}finally{busy.value=false;desktop.setState({busy:false,dirty:dirty.value})}}
async function activate(p:Publication,disable=false){
 if(data.value?.bindingRequired&&!disable){publishTarget.value=p;const possible=data.value.deployments?.filter(d=>d.services.some(s=>s.serviceId===p.manifest.serviceId&&s.version===p.manifest.version&&s.manifestDigest===p.digest&&s.contractDigest===p.contractDigest))||[];endpointChoice.value=possible.find(d=>d.endpointRef===p.binding?.endpointRef)?.endpointRef||(possible.length===1?possible[0].endpointRef:'');initialEndpoint.value=endpointChoice.value;return;}
 const active=data.value?.items.find(item=>item.manifest.serviceId===p.manifest.serviceId&&item.active);
 const breaking=compareServiceVersions(active?.manifest,p.manifest).filter(change=>change.breaking);
 const contractReview=compareContractVersions(active?.contract,p.contract,p.manifest).filter(change=>change.requiresReview);
 const description=disable?'停用后，经过统一出口的新调用将被拒绝。':`将统一出口切换到 ${p.manifest.name} ${p.manifest.version}。${breaking.length?`涉及 ${breaking.length} 项不兼容变化：${breaking.map(change=>change.description).join('；')}。请确认调用方已完成适配。`:'请确认提供方已部署对应接口。'}`;
 try{await ElMessageBox.confirm(description+(disable||!contractReview.length?'':`另有 ${contractReview.length} 项参数或响应契约变化，请先审阅详情。`),disable?'停用服务':breaking.length?'确认不兼容版本':contractReview.length?'确认契约变化':'启用版本',{confirmButtonText:disable?'停用':breaking.length?'确认已适配并启用':contractReview.length?'确认已审阅并启用':'启用',cancelButtonText:'取消',type:'warning'});await client.request('/activation'+environmentQuery(),{method:'POST',body:JSON.stringify({serviceId:p.manifest.serviceId,version:disable?null:p.manifest.version,expectedRevision:p.activeRevision,allowBreaking:breaking.length>0,allowContractChange:contractReview.length>0})});selected.value=null;await load();ElMessage.success('服务出口已更新')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}
}
async function publishDeployment(){
 const p=publishTarget.value,deployment=chosenDeployment.value;if(!p||!deployment||busy.value)return;
 const previous=data.value?.items.find(item=>item.manifest.serviceId===p.manifest.serviceId&&item.active);
 const breaking=compareServiceVersions(previous?.manifest,p.manifest).some(c=>c.breaking),contractReview=compareContractVersions(previous?.contract,p.contract,p.manifest).some(c=>c.requiresReview);
 try{
  await ElMessageBox.confirm(`将 ${environmentLabel.value}环境中的 ${p.manifest.name} ${p.manifest.version} 发布到 ${deployment.name}（${deployment.deploymentId}）。${breaking||contractReview?'存在接口或契约变化，请确认已审阅差异并完成调用方适配。':''}`,'确认环境发布',{confirmButtonText:breaking||contractReview?'确认已审阅并发布':'确认发布',cancelButtonText:'取消',type:'warning'});
  busy.value=true;
  await client.request('/activation'+environmentQuery(),{method:'POST',body:JSON.stringify({serviceId:p.manifest.serviceId,version:p.manifest.version,expectedRevision:p.activeRevision,endpointRef:deployment.endpointRef,expectedDeploymentDigest:deployment.digest,allowBreaking:breaking,allowContractChange:contractReview})});
  publishTarget.value=null;selected.value=null;await load();ElMessage.success('目标环境的服务部署已发布');
 }catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{busy.value=false}
}
function exportContract(p:Publication){if(!p.contract)return;const url=URL.createObjectURL(new Blob([JSON.stringify(p.contract,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${p.manifest.serviceId}-${p.manifest.version}.openapi.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportManifest(p:Publication){const url=URL.createObjectURL(new Blob([JSON.stringify(p.manifest,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${p.manifest.serviceId}-${p.manifest.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function drawerVisible(value:boolean){if(!value)selected.value=null}
function example(p:Publication,op:ServiceManifest['operations'][number]){return serviceInvocationUrl(desktop.origin,p.manifest.serviceId,op.operationId,Object.fromEntries([...op.path.matchAll(/\{(\w+)\}/g)].map(m=>[m[1],'资源ID'])))}
onMounted(load);
</script>
<template>
 <ConfiguredApplicationShell :config="application" :assets="{}" :active-path="route.path" :title="page.title" @navigate="navigate">
  <PageFrame>
   <template #header><PageHeading :title="page.title" :description="page.description"><template #actions><el-select v-if="data?.environments && data.environments.length>1" :model-value="selectedEnvironment" aria-label="目标环境" style="width:130px" :disabled="busy" @change="switchEnvironment"><el-option v-for="environment in data.environments" :key="environment.id" :label="environment.name+'环境'" :value="environment.id"/></el-select><el-tag v-else-if="environmentLabel" type="info" aria-label="当前运行环境">{{environmentLabel}}环境</el-tag><el-button :loading="loading" :disabled="busy" @click="load">刷新</el-button><el-button v-if="data?.canManage && route.path!='/register'" type="primary" @click="navigate('/register')">注册服务</el-button></template></PageHeading></template>
   <el-alert v-if="error" :title="error" type="error" :closable="false" show-icon/>
   <ContentPanel v-if="!data"><el-skeleton v-if="loading" :rows="6" animated/><el-empty v-else description="服务目录暂时不可用"><el-button @click="load">重试</el-button></el-empty></ContentPanel>
   <template v-if="data">
    <ContentPanel v-if="route.path==='/services'" v-loading="loading">
     <template #toolbar>
      <el-input v-model="search" aria-label="搜索服务" placeholder="搜索服务名称、应用或描述" clearable class="service-search"/>
      <el-select v-model="provider" aria-label="提供应用" placeholder="全部提供应用" clearable class="service-provider"><el-option v-for="app in providers" :key="app" :label="app" :value="app"/></el-select>
      <span class="service-count">{{serviceCount}} 个服务 · {{data.items.filter(p=>p.active).length}} 个启用版本</span>
     </template>
     <el-table :data="paged" empty-text="没有匹配的服务" row-key="digest">
      <el-table-column label="服务名称" min-width="220"><template #default="{row}"><el-button link type="primary" @click="selected=row">{{row.manifest.name}}</el-button><div class="secondary">{{row.manifest.serviceId}}</div></template></el-table-column>
      <el-table-column label="提供应用" min-width="165"><template #default="{row}">{{row.manifest.appId}}</template></el-table-column>
      <el-table-column label="版本" width="95"><template #default="{row}">{{row.manifest.version}}</template></el-table-column>
      <el-table-column label="接口数" width="85"><template #default="{row}">{{row.manifest.operations.length}}</template></el-table-column>
      <el-table-column label="契约" width="105"><template #default="{row}"><el-tag :type="row.contract?'success':'info'" size="small">{{row.contract?'OpenAPI':'仅清单'}}</el-tag></template></el-table-column>
      <el-table-column label="当前环境" width="105"><template #default="{row}"><el-tag :type="row.active?'success':'info'" size="small">{{row.active?'已启用':'未启用'}}</el-tag></template></el-table-column>
      <el-table-column label="生命周期" width="110"><template #default="{row}"><el-tag :type="row.lifecycle?.status==='deprecated'?'warning':row.lifecycle?.status==='retired'?'danger':'info'" size="small">{{lifecycleLabels[row.lifecycle?.status as keyof typeof lifecycleLabels]||'已发布'}}</el-tag></template></el-table-column>
      <el-table-column label="操作" :width="data.bindingRequired?275:215" fixed="right"><template #default="{row}"><el-button link type="primary" @click="selected=row">详情</el-button><el-button link @click="exportManifest(row)">下载清单</el-button><template v-if="data.canManage"><el-button v-if="data.bindingRequired" link type="primary" :disabled="['deprecated','retired'].includes(row.lifecycle?.status)" @click="activate(row)">发布部署</el-button><el-button v-if="row.active||!data.bindingRequired" link :disabled="!row.active&&['deprecated','retired'].includes(row.lifecycle?.status)" :type="row.active?'danger':'primary'" @click="activate(row,row.active)">{{row.active?'停用':'启用'}}</el-button></template></template></el-table-column>
     </el-table>
     <p class="service-note">调用使用当前用户身份，提供应用继续校验数据权限。后台机器身份调用尚未开放。</p>
     <template #footer><el-pagination v-model:current-page="pageNumber" :page-size="pageSize" :total="filtered.length" layout="total, prev, pager, next"/></template>
    </ContentPanel>
    <template v-else-if="route.path==='/activity'">
     <ContentPanel title="最近调用"><template #toolbar><span class="service-note">最近 300 次已转发请求；仅记录操作、状态和耗时。</span></template>
      <el-table :data="data.activity" empty-text="尚无经过统一出口的调用"><el-table-column label="时间" width="185"><template #default="{row}">{{new Date(row.at).toLocaleString('zh-CN')}}</template></el-table-column><el-table-column prop="serviceId" label="服务" min-width="200"/><el-table-column prop="operationId" label="操作" min-width="130"/><el-table-column prop="status" label="HTTP 状态" width="110"/><el-table-column prop="durationMs" label="耗时（ms）" width="120"/></el-table>
     </ContentPanel>
     <ContentPanel v-if="data.canManage" title="服务变更"><el-table :data="data.audit" empty-text="尚无人工变更"><el-table-column prop="serviceId" label="服务" min-width="220"/><el-table-column prop="version" label="版本" width="100"/><el-table-column label="操作" width="110"><template #default="{row}">{{row.action==='activate'&&row.binding?'发布部署':({publish:'登记版本',activate:'启用版本',disable:'停用服务',lifecycle:'生命周期'} as Record<string,string>)[row.action]||row.action}}</template></el-table-column><el-table-column v-if="data.bindingRequired" label="部署变更" min-width="300"><template #default="{row}"><span v-if="row.previousBinding">{{row.previousBinding.deploymentId}}（{{row.previousBinding.endpointRef}}） → </span>{{row.binding?row.binding.deploymentId+'（'+row.binding.endpointRef+'）':row.previousBinding?'已停用':'—'}}</template></el-table-column><el-table-column label="生命周期变更（所有环境）" min-width="280"><template #default="{row}"><template v-if="row.lifecycle">{{row.previousLifecycle?lifecycleLabels[row.previousLifecycle.status as keyof typeof lifecycleLabels]+' → ':''}}{{lifecycleLabels[row.lifecycle.status as keyof typeof lifecycleLabels]}}<p class="service-note">{{row.lifecycle.reason}}</p><span v-if="row.lifecycle.retireAfter">计划退役：{{row.lifecycle.retireAfter}}</span></template><span v-else>—</span></template></el-table-column><el-table-column label="时间" width="180"><template #default="{row}">{{new Date(row.at).toLocaleString('zh-CN')}}</template></el-table-column></el-table></ContentPanel>
    </template>
    <ContentPanel v-else title="导入服务清单">
     <template v-if="data.canManage" #toolbar><el-button :disabled="busy" @click="importInput?.click()">导入登记包</el-button><input ref="importInput" type="file" accept="application/json,.json" hidden @change="importRegistration"/><span class="service-note">选择包含清单与契约的 registration.json，在提交前可继续编辑。</span></template>
     <template v-if="data.canManage"><el-form label-position="top"><el-form-item label="应用服务清单"><el-input v-model="draft" aria-label="应用服务清单" type="textarea" :rows="18" placeholder="粘贴 services/manifest.json 的内容"/></el-form-item><el-form-item label="OpenAPI 3.1.1 契约（可选）"><el-input v-model="contractDraft" aria-label="OpenAPI 契约" type="textarea" :rows="12" placeholder="粘贴 services/openapi.json，与清单版本一致并覆盖全部接口"/></el-form-item></el-form><p class="service-note">清单声明应用、服务版本和接口，不包含服务器地址或凭据。契约仅接受文档内 components 引用，最多 512 KiB，使用 JSON Schema 2020-12。清单与契约的同版本内容均不可覆盖；登记完成后，在目录中启用新版本。</p></template><el-empty v-else description="当前账号没有服务维护权限"/>
     <template v-if="data.canManage" #footer><el-button @click="navigate('/services')">取消</el-button><el-button type="primary" :loading="busy" :disabled="!draft.trim()" @click="publish">校验并登记</el-button></template>
    </ContentPanel>
   </template>
  </PageFrame>
  <el-dialog :model-value="!!publishTarget" title="发布到环境" width="min(660px,94vw)" :before-close="closePublish" :close-on-click-modal="false" :close-on-press-escape="!busy">
   <template v-if="publishTarget"><el-descriptions :column="1" border><el-descriptions-item label="目标环境">{{environmentLabel}}环境</el-descriptions-item><el-descriptions-item label="服务版本">{{publishTarget.manifest.name}} {{publishTarget.manifest.version}}</el-descriptions-item></el-descriptions><el-form label-position="top" style="margin-top:20px"><el-form-item label="已部署且契约匹配的目标"><el-select v-model="endpointChoice" aria-label="目标部署" placeholder="选择部署" :disabled="busy" style="width:100%"><el-option v-for="deployment in endpointOptions" :key="deployment.endpointRef" :label="deployment.name+' · '+deployment.deploymentId" :value="deployment.endpointRef"/></el-select></el-form-item></el-form><el-alert v-if="!endpointOptions.length" type="warning" :closable="false" title="此环境尚无匹配的部署。请先部署对应程序并由发布工具登记，再发布服务。"/><el-descriptions v-if="chosenDeployment" :column="1" border><el-descriptions-item label="实际提供方">{{chosenDeployment.providerAppId}}</el-descriptions-item><el-descriptions-item label="运行资源">{{chosenDeployment.resourceRef}}</el-descriptions-item><el-descriptions-item label="受控地址">{{chosenDeployment.baseUrl}}</el-descriptions-item><el-descriptions-item label="部署时间">{{new Date(chosenDeployment.deployedAt).toLocaleString('zh-CN')}}</el-descriptions-item></el-descriptions><p class="service-note">发布会更新所选环境的服务出口；不会执行程序部署。后台会再次校验部署记录、契约摘要和修订号。</p></template>
   <template #footer><el-button :disabled="busy" @click="closePublish()">取消</el-button><el-button type="primary" :loading="busy" :disabled="!chosenDeployment" @click="publishDeployment">发布到{{environmentLabel}}环境</el-button></template>
  </el-dialog>
  <el-dialog :model-value="!!lifecycleTarget" title="管理版本生命周期" width="min(620px,94vw)" :before-close="closeLifecycle" :close-on-click-modal="false" :close-on-press-escape="!busy">
   <template v-if="lifecycleTarget"><p>{{lifecycleTarget.manifest.name}} · {{lifecycleTarget.manifest.version}}</p><el-alert type="info" :closable="false" title="生命周期对所有环境生效，环境启用状态仍独立管理。"/><el-form label-position="top" style="margin-top:20px" :disabled="busy"><el-form-item label="目标状态"><el-select v-model="lifecycleStatus" aria-label="生命周期目标状态" style="width:100%"><el-option v-for="status in lifecycleChoices" :key="status" :value="status" :label="status==='published'?'恢复维护（已发布）':lifecycleLabels[status as keyof typeof lifecycleLabels]"/></el-select></el-form-item><el-form-item label="变更说明与迁移安排" required><el-input v-model="lifecycleReason" aria-label="生命周期变更说明" type="textarea" :rows="4" maxlength="2000" show-word-limit placeholder="说明变更原因、替代版本及调用方迁移安排"/></el-form-item><el-form-item v-if="lifecycleStatus==='deprecated'" label="计划退役日期（UTC，可选）"><el-date-picker v-model="retireAfter" aria-label="计划退役日期" type="date" value-format="YYYY-MM-DD" placeholder="选择日期"/></el-form-item></el-form><p class="service-note">弃用保留现有调用，禁止新增或更换环境绑定。到期不会自动停服；退役前必须让所有环境停止使用该版本。退役保留契约和审计，不能恢复。</p></template>
   <template #footer><el-button :disabled="busy" @click="closeLifecycle()">取消</el-button><el-button type="primary" :loading="busy" :disabled="!lifecycleReason.trim()" @click="saveLifecycle">提交变更</el-button></template>
  </el-dialog>
  <el-drawer :model-value="!!selected" @update:model-value="drawerVisible" :title="selected?.manifest.name" size="min(820px, 94vw)">
   <section v-if="selected?.lifecycle" class="service-operation"><h3>版本生命周期 · {{lifecycleLabels[selected.lifecycle.status]}}</h3><p>{{selected.lifecycle.reason}}</p><p v-if="selected.lifecycle.retireAfter" class="service-note">计划退役日期：{{selected.lifecycle.retireAfter}}（UTC），到期仍需明确退役。</p><p class="service-note">{{new Date(selected.lifecycle.at).toLocaleString('zh-CN')}} 更新 · 对所有环境生效</p><el-alert v-if="selected.lifecycle.status==='deprecated'" type="warning" :closable="false" title="此版本已弃用，现有调用保留；请按迁移安排升级。"/><el-alert v-if="selected.lifecycle.status==='retired'" type="info" :closable="false" title="此版本已退役，契约与变更历史保留供查询。"/><el-button v-if="data?.canManage&&selected.lifecycle.status!=='retired'" style="margin-top:12px" @click="editLifecycle(selected)">管理生命周期</el-button></section>
   <template v-if="selected"><el-descriptions :column="1" border><el-descriptions-item label="服务 ID">{{selected.manifest.serviceId}}</el-descriptions-item><el-descriptions-item label="提供应用">{{selected.manifest.appId}}</el-descriptions-item><el-descriptions-item label="版本">{{selected.manifest.version}}</el-descriptions-item><el-descriptions-item v-if="data?.bindingRequired" label="目标环境">{{environmentLabel}}环境</el-descriptions-item><el-descriptions-item v-if="selected.active && selected.binding" label="当前部署">{{selected.binding.deploymentId}} · {{selected.binding.endpointRef}}</el-descriptions-item></el-descriptions>
    <section class="service-operation"><h3>版本差异</h3><el-select v-model="comparisonBase" aria-label="对比基准版本" :placeholder="`当前启用版本（${selected.activeVersion||'未启用'}）`"><el-option value="" :label="`当前启用版本（${selected.activeVersion||'未启用'}）`"/><el-option v-for="version in versions" :key="version.digest" :label="version.manifest.version" :value="version.manifest.version"/></el-select><p class="service-note">{{baseline?.manifest.version||'无已启用版本'}} → {{selected.manifest.version}}。请求检查新版是否仍接受旧输入，响应检查新输出是否符合旧结构。结构兼容不代表业务行为已验证；认证、编码、复杂约束及未提供契约的历史版本仍需单独核对。</p><el-table :data="changes" empty-text="接口列表没有变化"><el-table-column prop="operationId" label="操作" min-width="120"/><el-table-column prop="description" label="变化" min-width="240"/><el-table-column label="影响" width="115"><template #default="{row}"><el-tag :type="row.breaking?'danger':'info'">{{row.breaking?'需要适配':'兼容变化'}}</el-tag></template></el-table-column></el-table><el-table :data="contractChanges" empty-text="契约无变化或双方均未提供契约"><el-table-column prop="operationId" label="契约操作" min-width="120"/><el-table-column prop="description" label="契约变化" min-width="240"/><el-table-column prop="path" label="结构位置" min-width="210" show-overflow-tooltip/><el-table-column label="影响" width="115"><template #default="{row}"><el-tag :type="row.requiresReview?'warning':'info'">{{row.requiresReview?'需要审阅':row.assessment==='compatible'?'结构兼容':'无结构基准'}}</el-tag></template></el-table-column></el-table></section>
    <section v-if="selected.contract" class="service-operation"><h3>接口文档</h3><p class="service-note">OpenAPI {{selected.contract.openapi}} · {{selected.contract.info.description}}</p><el-button @click="exportContract(selected)">下载 OpenAPI</el-button><details><summary>公共数据结构</summary><div v-for="(schema,name) in selected.contract.components?.schemas" :key="name"><h4>{{name}}</h4><pre>{{JSON.stringify(schema,null,2)}}</pre></div></details></section>
    <div v-for="op in selected.manifest.operations" :key="op.operationId" class="service-operation"><div class="operation-heading"><el-tag :type="op.effect==='read'?'success':'warning'" size="small">{{op.method}}</el-tag><code>{{op.path}}</code></div><h3>{{op.summary}}</h3><p class="service-note">操作 ID：{{op.operationId}} · {{op.effect==='read'?'读取':'修改数据'}}</p><label class="endpoint-label">统一调用出口</label><pre>{{example(selected,op)}}</pre><el-button v-if="selected.active && (!data?.runningEnvironment || data.runningEnvironment===selectedEnvironment) && op.method==='GET' && !op.path.includes('{')" :loading="checking===op.operationId" @click="check(selected,op)">验证只读调用</el-button><p v-if="checkResult && checked===op.operationId" class="service-note" role="status">{{checkResult}}</p><p class="service-note">请求方法保持 {{op.method}}，正文与业务接口一致。写操作需要会话 CSRF，路径变量通过 path.变量名 传入。</p><ContractOperation v-if="selected.contract" :contract="selected.contract" :operation="op"/></div>
   </template>
  </el-drawer>
 </ConfiguredApplicationShell>
</template>
