<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch,nextTick} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {ConfiguredApplicationShell,PageFrame,PageHeading,ContentPanel,compareServiceVersions,compareContractVersions,serviceInvocationUrl} from '@mg-inside/frontend';
import {Refresh,Plus,Download} from '@element-plus/icons-vue';
import {ElMessage,ElMessageBox} from 'element-plus';
import {application} from './main';
import {client,desktop,serviceOrigin} from './api';
import {categories,categoryName,dateTime,type Catalog,type Publication,type Workspace,type Lifecycle} from './models';
import ServiceCatalog from './ServiceCatalog.vue';
import ServiceTags from './ServiceTags.vue';
import ServiceInsights from './ServiceInsights.vue';
import RegistrationEditor from './RegistrationEditor.vue';
import ContractOperation from './ContractOperation.vue';

const route=useRoute(),router=useRouter(),data=ref<Catalog|null>(null),workspace=ref<Workspace|null>(null);
const loading=ref(false),error=ref(''),workspaceError=ref(''),environment=ref(''),saving=ref(false),childDirty=ref(false),childBusy=ref(false),editorKey=ref(0);
const source=ref<Publication|null>(null),selected=ref<Publication|null>(null),detailTab=ref('overview'),operationId=ref(''),comparisonBase=ref('');
const metadata=ref<Publication|null>(null),category=ref('uncategorized'),owner=ref(''),metadataInitial=ref('');
const publishTarget=ref<Publication|null>(null),endpoint=ref(''),endpointInitial=ref('');
const lifecycleTarget=ref<Publication|null>(null),lifecycleStatus=ref<Lifecycle['status']>('deprecated'),reason=ref(''),retireAfter=ref(''),lifecycleInitial=ref('');
const labels={draft:'草稿',published:'已发布',deprecated:'已弃用',retired:'已退役'};
const page=computed(()=>application.pages.find(p=>p.path===route.path)||application.pages[0]);
const environmentLabel=computed(()=>data.value?.environments?.find(e=>e.id===environment.value)?.name||({local:'本地',development:'开发',testing:'测试',production:'生产'} as Record<string,string>)[environment.value]||environment.value);
const query=()=>environment.value?'?environment='+encodeURIComponent(environment.value):'';
const metaSnapshot=()=>JSON.stringify([category.value,owner.value]);
const lifeSnapshot=()=>JSON.stringify([lifecycleStatus.value,reason.value,retireAfter.value]);
const dirty=computed(()=>childDirty.value||!!metadata.value&&metaSnapshot()!==metadataInitial.value||!!publishTarget.value&&endpoint.value!==endpointInitial.value||!!lifecycleTarget.value&&lifeSnapshot()!==lifecycleInitial.value);
const busy=computed(()=>saving.value||childBusy.value);
const versions=computed(()=>data.value?.items.filter(p=>p.manifest.serviceId===selected.value?.manifest.serviceId)||[]);
const baseline=computed(()=>versions.value.find(p=>comparisonBase.value?p.manifest.version===comparisonBase.value:p.active));
const changes=computed(()=>selected.value?compareServiceVersions(baseline.value?.manifest,selected.value.manifest):[]);
const contractChanges=computed(()=>selected.value?compareContractVersions(baseline.value?.contract,selected.value.contract,selected.value.manifest):[]);
const activeOperation=computed(()=>selected.value?.manifest.operations.find(o=>o.operationId===operationId.value));
const endpointOptions=computed(()=>data.value?.deployments?.filter(d=>d.services.some(s=>s.serviceId===publishTarget.value?.manifest.serviceId&&s.version===publishTarget.value?.manifest.version&&s.manifestDigest===publishTarget.value?.digest&&s.contractDigest===publishTarget.value?.contractDigest))||[]);
const chosenDeployment=computed(()=>endpointOptions.value.find(d=>d.endpointRef===endpoint.value));
const lifecycleChoices=computed(()=>lifecycleTarget.value?.lifecycle?.status==='draft'?['retired']:lifecycleTarget.value?.lifecycle?.status==='deprecated'?['deprecated','published','retired']:['deprecated']);
let loadRun=0,controller:AbortController|undefined;
async function load(){const run=++loadRun;controller?.abort();controller=new AbortController();loading.value=true;error.value='';try{const result=await client.request<Catalog>(query(),{signal:controller.signal});if(run!==loadRun)return;data.value=result;environment.value=result.storage?.environment||environment.value;try{const result=await client.request<Workspace>('/workspace'+query(),{signal:controller.signal});if(run===loadRun){workspace.value=result;workspaceError.value='';}}catch(e){if(run===loadRun&&(e as Error).name!=='AbortError'){workspace.value=null;workspaceError.value=(e as Error).message;}}}catch(e){if(run===loadRun&&(e as Error).name!=='AbortError')error.value=(e as Error).message;}finally{if(run===loadRun)loading.value=false;}}
async function confirmDiscard(){try{await ElMessageBox.confirm('有尚未提交的服务更改，确定放弃吗？','未提交更改',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'});return true;}catch{return false;}}
async function canLeave(){if(busy.value)return false;if(dirty.value&&!await confirmDiscard())return false;childDirty.value=false;metadata.value=null;publishTarget.value=null;lifecycleTarget.value=null;editorKey.value++;return true;}
function childState(d:boolean,b:boolean){childDirty.value=d;childBusy.value=b;}
async function navigate(path:string){if(route.path!==path)await router.push(path);}
async function switchEnvironment(value:string){if(value===environment.value||!await canLeave())return;environment.value=value;selected.value=null;data.value=null;workspace.value=null;await load();}
function select(p:Publication,op?:string){selected.value=p;operationId.value=op||p.manifest.operations[0]?.operationId||'';detailTab.value=op?'apis':'overview';comparisonBase.value='';}
function drawerVisible(value:boolean){if(!value)selected.value=null;}
function selectVersion(value:string){const p=versions.value.find(p=>p.manifest.version===value);if(p)select(p);}
async function register(p?:Publication){if(!await canLeave())return;source.value=p||null;selected.value=null;await router.push('/register');}
async function registered(){childDirty.value=false;childBusy.value=false;await nextTick();childDirty.value=false;await router.push('/services');source.value=null;await load();}
function editMetadata(p:Publication){metadata.value=p;category.value=workspace.value?.services[p.manifest.serviceId]?.category||'uncategorized';owner.value=workspace.value?.services[p.manifest.serviceId]?.owner||'';metadataInitial.value=metaSnapshot();}
async function closeMetadata(done?:()=>void){if(busy.value||metaSnapshot()!==metadataInitial.value&&!await confirmDiscard())return;metadata.value=null;done?.();}
async function saveMetadata(){if(!metadata.value||!workspace.value||busy.value)return;saving.value=true;try{workspace.value=await client.request<Workspace>('/workspace'+query(),{method:'POST',body:JSON.stringify({kind:'service',expectedRevision:workspace.value.revision,serviceId:metadata.value.manifest.serviceId,category:category.value,owner:owner.value})});metadata.value=null;ElMessage.success('服务信息已保存');}catch(e){ElMessage.error((e as Error).message);}finally{saving.value=false;}}
function editLifecycle(p:Publication){if(!p.lifecycle||p.lifecycle.status==='retired')return;lifecycleTarget.value=p;lifecycleStatus.value=p.lifecycle.status==='draft'?'retired':'deprecated';reason.value=p.lifecycle.status==='deprecated'?p.lifecycle.reason:'';retireAfter.value=p.lifecycle.retireAfter||'';lifecycleInitial.value=lifeSnapshot();}
async function closeLifecycle(done?:()=>void){if(busy.value||lifeSnapshot()!==lifecycleInitial.value&&!await confirmDiscard())return;lifecycleTarget.value=null;done?.();}
async function saveLifecycle(){const p=lifecycleTarget.value;if(!p?.lifecycle||busy.value||!reason.value.trim())return;try{await ElMessageBox.confirm(`将 ${p.manifest.name} ${p.manifest.version} 标记为${labels[lifecycleStatus.value]}，对所有环境生效。${lifecycleStatus.value==='retired'?'退役要求所有环境停止使用，完成后不可恢复。':lifecycleStatus.value==='deprecated'?'保留现有调用，禁止新增或更换环境绑定。':'恢复后可再次发布此版本。'}`,'确认生命周期变更',{type:'warning',confirmButtonText:'确认变更',cancelButtonText:'取消'});saving.value=true;await client.request('/lifecycle'+query(),{method:'POST',body:JSON.stringify({serviceId:p.manifest.serviceId,version:p.manifest.version,status:lifecycleStatus.value,reason:reason.value.trim(),expectedRevision:p.lifecycle.revision,...(lifecycleStatus.value==='deprecated'&&retireAfter.value?{retireAfter:retireAfter.value}:{})})});lifecycleTarget.value=null;selected.value=null;await load();ElMessage.success('生命周期已更新');}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message);}finally{saving.value=false;}}
function review(p:Publication){const previous=data.value?.items.find(item=>item.manifest.serviceId===p.manifest.serviceId&&item.active);return {allowBreaking:compareServiceVersions(previous?.manifest,p.manifest).some(c=>c.breaking),allowContractChange:compareContractVersions(previous?.contract,p.contract,p.manifest).some(c=>c.requiresReview)};}
async function activate(p:Publication,disable=false){if(busy.value)return;if(data.value?.bindingRequired&&!disable){publishTarget.value=p;endpoint.value=endpointOptions.value.find(d=>d.endpointRef===p.binding?.endpointRef)?.endpointRef||(endpointOptions.value.length===1?endpointOptions.value[0].endpointRef:'');endpointInitial.value=endpoint.value;return;}const flags=review(p);try{await ElMessageBox.confirm(disable?'停用后，经过统一出口的新调用将被拒绝。':`将出口切换至 ${p.manifest.name} ${p.manifest.version}。${flags.allowBreaking||flags.allowContractChange?'存在接口或契约变化，请确认已审阅差异并完成调用方适配。':'请确认提供方已部署对应接口。'}`,disable?'停用服务':'确认启用版本',{type:'warning',confirmButtonText:disable?'停用':'确认并启用',cancelButtonText:'取消'});saving.value=true;await client.request('/activation'+query(),{method:'POST',body:JSON.stringify({serviceId:p.manifest.serviceId,version:disable?null:p.manifest.version,expectedRevision:p.activeRevision,...flags})});selected.value=null;await load();ElMessage.success('服务出口已更新');}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message);}finally{saving.value=false;}}
async function closePublish(done?:()=>void){if(busy.value||endpoint.value!==endpointInitial.value&&!await confirmDiscard())return;publishTarget.value=null;done?.();}
async function publishDeployment(){const p=publishTarget.value,d=chosenDeployment.value;if(!p||!d||busy.value)return;const flags=review(p);try{await ElMessageBox.confirm(`将 ${environmentLabel.value}环境的 ${p.manifest.name} ${p.manifest.version} 发布到 ${d.name}（${d.deploymentId}）。${flags.allowBreaking||flags.allowContractChange?'存在接口或契约变化，请确认已审阅并完成适配。':''}`,'确认环境发布',{type:'warning',confirmButtonText:'确认并发布',cancelButtonText:'取消'});saving.value=true;await client.request('/activation'+query(),{method:'POST',body:JSON.stringify({serviceId:p.manifest.serviceId,version:p.manifest.version,expectedRevision:p.activeRevision,endpointRef:d.endpointRef,expectedDeploymentDigest:d.digest,...flags})});publishTarget.value=null;selected.value=null;await load();ElMessage.success('目标环境已发布');}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message);}finally{saving.value=false;}}
function download(p:Publication,contract=false){const url=URL.createObjectURL(new Blob([JSON.stringify(contract?p.contract:p.manifest,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${p.manifest.serviceId}-${p.manifest.version}${contract?'.openapi':''}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function logs(){const p=selected.value;if(!p)return;selected.value=null;await router.push({path:'/activity',query:{serviceId:p.manifest.serviceId,...(detailTab.value==='apis'?{operationId:operationId.value}:{})}});}
const checking=ref(false),checkResult=ref('');let checkRun=0;
watch([selected,operationId],()=>{checkRun++;checking.value=false;checkResult.value='';});
async function check(){const p=selected.value,op=activeOperation.value;if(!p||!op)return;const run=++checkRun;checking.value=true;try{await client.invoke(p.manifest.serviceId,op.operationId);if(run===checkRun)checkResult.value='调用成功';}catch(e){if(run===checkRun)checkResult.value=(e as Error).message;}finally{if(run===checkRun)checking.value=false;}}
const example=computed(()=>selected.value?.manifest.exposure!=='catalog'&&selected.value&&activeOperation.value?serviceInvocationUrl(serviceOrigin,selected.value.manifest.serviceId,activeOperation.value.operationId,Object.fromEntries([...activeOperation.value.path.matchAll(/\{(\w+)\}/g)].map(m=>[m[1],'资源ID']))):'');
desktop.configure({onClose:canLeave,onNavigate:async path=>{await router.push(path);}});
const removeGuard=router.beforeEach(async(to,from)=>to.path===from.path||await canLeave());
const beforeUnload=(event:BeforeUnloadEvent)=>{if(dirty.value||busy.value){event.preventDefault();event.returnValue='';}};
window.addEventListener('beforeunload',beforeUnload);
watch([dirty,busy],()=>desktop.setState({dirty:dirty.value,busy:busy.value}));
onUnmounted(()=>{loadRun++;controller?.abort();removeGuard();window.removeEventListener('beforeunload',beforeUnload);});onMounted(load);
</script>

<template>
 <ConfiguredApplicationShell :config="application" :assets="{}" :active-path="route.path" :title="page.title" @navigate="navigate">
  <PageFrame>
   <template #header><PageHeading :title="page.title"><template #actions><el-select v-if="data?.environments&&data.environments.length>1" :model-value="environment" aria-label="目标环境" class="environment-select" :disabled="busy" @change="switchEnvironment"><el-option v-for="item in data.environments" :key="item.id" :value="item.id" :label="item.name+'环境'"/></el-select><el-tag v-else-if="environmentLabel" type="info">{{environmentLabel}}环境</el-tag><el-tooltip content="刷新目录"><el-button :icon="Refresh" circle aria-label="刷新目录" :loading="loading" :disabled="busy||dirty" @click="load"/></el-tooltip><el-button v-if="data?.canManage&&route.path!=='/register'" type="primary" :icon="Plus" :disabled="busy" @click="register()">注册服务</el-button></template></PageHeading></template>
   <el-alert v-if="error" :title="error" type="error" :closable="false" show-icon/>
   <el-alert v-if="workspaceError" :title="'分类与标签暂不可用：'+workspaceError" type="warning" :closable="false" show-icon/>
   <ContentPanel v-if="!data"><el-skeleton v-if="loading" :rows="6" animated/><el-empty v-else description="服务目录暂时不可用"><el-button @click="load">重试</el-button></el-empty></ContentPanel>
   <template v-else>
    <ServiceCatalog v-if="route.path==='/services'" :data="data" :workspace="workspace" :loading="loading" :environment="environment" @select="select" @metadata="editMetadata"/>
    <ServiceInsights v-else-if="route.path==='/activity'" :key="environment+String(route.query.serviceId)+String(route.query.operationId)" :data="data" :environment="environment" :service-id="String(route.query.serviceId||'')" :operation-id="String(route.query.operationId||'')"/>
    <template v-else-if="route.path==='/services/tags'"><ServiceTags v-if="workspace" :key="editorKey" :data="data" :workspace="workspace" :environment="environment" @saved="load" @state="childState"/><el-empty v-else description="标签目录暂时不可用"><el-button @click="load">重试</el-button></el-empty></template>
    <RegistrationEditor v-else-if="route.path==='/register'" :key="editorKey" :source="source" :data="data" :environment="environment" @saved="registered" @cancel="navigate('/services')" @state="childState"/>
   </template>
  </PageFrame>
  <el-dialog :model-value="!!metadata" title="分类与负责人" width="min(520px,94vw)" :before-close="closeMetadata" :close-on-click-modal="false"><el-form label-position="top" :disabled="busy"><el-form-item label="服务">{{metadata?.manifest.name}}</el-form-item><el-form-item label="分类"><el-select v-model="category" aria-label="服务分类"><el-option v-for="item in categories" :key="item.id" :value="item.id" :label="item.name"/></el-select></el-form-item><el-form-item label="负责人"><el-input v-model="owner" maxlength="80" aria-label="服务负责人"/></el-form-item></el-form><template #footer><el-button :disabled="busy" @click="closeMetadata()">取消</el-button><el-button type="primary" :loading="saving" @click="saveMetadata">保存</el-button></template></el-dialog>
  <el-dialog :model-value="!!publishTarget" title="发布到环境" width="min(660px,94vw)" :before-close="closePublish" :close-on-click-modal="false" :close-on-press-escape="!busy">
   <template v-if="publishTarget"><el-descriptions :column="1" border><el-descriptions-item label="目标环境">{{environmentLabel}}环境</el-descriptions-item><el-descriptions-item label="服务版本">{{publishTarget.manifest.name}} {{publishTarget.manifest.version}}</el-descriptions-item></el-descriptions><el-form label-position="top" class="dialog-form"><el-form-item label="已部署且契约匹配的目标"><el-select v-model="endpoint" aria-label="目标部署" :disabled="busy"><el-option v-for="d in endpointOptions" :key="d.endpointRef" :value="d.endpointRef" :label="d.name+' · '+d.deploymentId"/></el-select></el-form-item></el-form><el-alert v-if="!endpointOptions.length" type="warning" :closable="false" title="当前环境尚无契约匹配的部署，请先登记对应程序部署。"/><el-descriptions v-if="chosenDeployment" :column="1" border><el-descriptions-item label="提供方">{{chosenDeployment.providerAppId}}</el-descriptions-item><el-descriptions-item label="运行资源">{{chosenDeployment.resourceRef}}</el-descriptions-item><el-descriptions-item label="受控地址">{{chosenDeployment.baseUrl}}</el-descriptions-item><el-descriptions-item label="部署时间">{{dateTime(chosenDeployment.deployedAt)}}</el-descriptions-item></el-descriptions></template>
   <template #footer><el-button :disabled="busy" @click="closePublish()">取消</el-button><el-button type="primary" :loading="saving" :disabled="!chosenDeployment" @click="publishDeployment">发布到{{environmentLabel}}环境</el-button></template>
  </el-dialog>
  <el-dialog :model-value="!!lifecycleTarget" title="管理版本生命周期" width="min(620px,94vw)" :before-close="closeLifecycle" :close-on-click-modal="false" :close-on-press-escape="!busy">
   <p>{{lifecycleTarget?.manifest.name}} · {{lifecycleTarget?.manifest.version}}</p><el-alert type="info" :closable="false" title="生命周期对所有环境生效。计划退役日期到期不会自动停服。"/><el-form label-position="top" class="dialog-form" :disabled="busy"><el-form-item label="目标状态"><el-select v-model="lifecycleStatus" aria-label="生命周期目标状态"><el-option v-for="status in lifecycleChoices" :key="status" :value="status" :label="labels[status as keyof typeof labels]"/></el-select></el-form-item><el-form-item label="变更说明与迁移安排" required><el-input v-model="reason" type="textarea" :rows="4" maxlength="2000" aria-label="生命周期变更说明"/></el-form-item><el-form-item v-if="lifecycleStatus==='deprecated'" label="计划退役日期（UTC）"><el-date-picker v-model="retireAfter" type="date" value-format="YYYY-MM-DD" aria-label="计划退役日期"/></el-form-item></el-form>
   <template #footer><el-button :disabled="busy" @click="closeLifecycle()">取消</el-button><el-button type="primary" :loading="saving" :disabled="!reason.trim()" @click="saveLifecycle">提交变更</el-button></template>
  </el-dialog>
  <el-drawer :model-value="!!selected" :title="selected?.manifest.name" size="min(1040px,96vw)" @update:model-value="drawerVisible">
   <template v-if="selected"><div class="service-toolbar"><el-select :model-value="selected.manifest.version" aria-label="详情版本" class="service-provider" @change="selectVersion"><el-option v-for="p in versions" :key="p.digest" :value="p.manifest.version" :label="p.manifest.version+(p.active?' · 当前启用':'')"/></el-select><el-tag :type="selected.active?'success':'info'">{{selected.active?'已启用':'未启用'}}</el-tag><el-tag type="info">{{labels[selected.lifecycle?.status||'published']}}</el-tag><el-button v-if="data?.canManage" :icon="Plus" :disabled="busy" @click="register(selected)">登记新版本</el-button><el-button link type="primary" @click="logs">调用日志</el-button></div>
    <el-tabs v-model="detailTab"><el-tab-pane name="overview" label="服务概览"/><el-tab-pane name="apis" label="API 文档"/><el-tab-pane name="versions" label="版本比较"/><el-tab-pane name="environment" label="环境发布"/><el-tab-pane v-if="data?.canManage" name="audit" label="变更记录"/></el-tabs>
    <template v-if="detailTab==='overview'"><el-descriptions :column="1" border><el-descriptions-item label="服务标识">{{selected.manifest.serviceId}}</el-descriptions-item><el-descriptions-item label="提供应用">{{data?.providers?.find(p=>p.id===selected?.manifest.appId)?.name||selected.manifest.appId}}</el-descriptions-item><el-descriptions-item label="描述">{{selected.manifest.description||'--'}}</el-descriptions-item><el-descriptions-item label="分类">{{categoryName(workspace?.services[selected.manifest.serviceId]?.category)}}</el-descriptions-item><el-descriptions-item label="负责人">{{workspace?.services[selected.manifest.serviceId]?.owner||'--'}}</el-descriptions-item><el-descriptions-item label="登记时间">{{dateTime(selected.at)}}</el-descriptions-item></el-descriptions><div class="service-toolbar dialog-form"><el-button :icon="Download" @click="download(selected)">下载清单</el-button><el-button v-if="selected.contract" :icon="Download" @click="download(selected,true)">下载 OpenAPI</el-button></div><section v-if="selected.lifecycle" class="service-operation"><h3>生命周期 · {{labels[selected.lifecycle.status]}}</h3><p>{{selected.lifecycle.reason}}</p><p v-if="selected.lifecycle.retireAfter">计划退役：{{selected.lifecycle.retireAfter}}</p><p class="secondary">{{dateTime(selected.lifecycle.at)}} · 所有环境</p><el-button v-if="data?.canManage&&selected.lifecycle.status!=='retired'" :disabled="busy" @click="editLifecycle(selected)">管理生命周期</el-button></section></template>
    <template v-else-if="detailTab==='apis'"><el-select v-model="operationId" aria-label="选择 API" class="operation-select"><el-option v-for="op in selected.manifest.operations" :key="op.operationId" :value="op.operationId" :label="op.summary+' · '+op.method+' '+op.path"/></el-select><section v-if="activeOperation" class="service-operation"><div class="operation-heading"><el-tag :type="activeOperation.method==='GET'?'success':'warning'">{{activeOperation.method}}</el-tag><code>{{activeOperation.path}}</code></div><h3>{{activeOperation.summary}}</h3><div class="tag-list"><el-tag v-for="tag in workspace?.tags.filter(t=>t.enabled&&t.references.some(r=>r.serviceId===selected?.manifest.serviceId&&r.operationId===operationId))||[]" :key="tag.id" :type="tag.color" size="small">{{tag.name}}</el-tag></div><p class="secondary">{{operationId}}</p><template v-if="selected.manifest.exposure!=='catalog'"><label class="endpoint-label">统一调用出口</label><pre>{{example}}</pre></template><el-tag v-else type="info">协议目录登记</el-tag><el-button v-if="selected.active&&environment===data?.runningEnvironment&&activeOperation.method==='GET'&&!activeOperation.path.includes('{')" :loading="checking" @click="check">验证只读调用</el-button><p v-if="checkResult" role="status">{{checkResult}}</p><ContractOperation v-if="selected.contract" :contract="selected.contract" :operation="activeOperation"/><el-empty v-else description="此版本尚未提供 OpenAPI 契约"/><details v-if="selected.contract?.components?.schemas"><summary>公共数据结构</summary><div v-for="(schema,name) in selected.contract.components.schemas" :key="name"><h4>{{name}}</h4><pre>{{JSON.stringify(schema,null,2)}}</pre></div></details></section></template>
    <template v-else-if="detailTab==='versions'"><div class="service-toolbar"><span>对比基准</span><el-select v-model="comparisonBase" aria-label="对比基准版本" class="service-provider"><el-option value="" :label="'当前启用版本（'+(selected.activeVersion||'无')+'）'"/><el-option v-for="p in versions" :key="p.digest" :value="p.manifest.version" :label="p.manifest.version"/></el-select><span class="secondary">{{baseline?.manifest.version||'无基准'}} → {{selected.manifest.version}}</span></div><el-table :data="changes" empty-text="接口列表没有变化"><el-table-column prop="operationId" label="操作" min-width="130"/><el-table-column prop="description" label="变化" min-width="250"/><el-table-column label="影响" width="110"><template #default="{row}"><el-tag :type="row.breaking?'danger':'info'">{{row.breaking?'需要适配':'兼容变化'}}</el-tag></template></el-table-column></el-table><el-table :data="contractChanges" empty-text="契约无变化或双方均未提供契约"><el-table-column prop="operationId" label="契约操作" min-width="130"/><el-table-column prop="description" label="契约变化" min-width="250"/><el-table-column prop="path" label="结构位置" min-width="180" show-overflow-tooltip/><el-table-column label="影响" width="120"><template #default="{row}"><el-tag :type="row.requiresReview?'warning':'info'">{{row.requiresReview?'需要审阅':row.assessment==='compatible'?'结构兼容':'无结构基准'}}</el-tag></template></el-table-column></el-table></template>
    <template v-else-if="detailTab==='environment'"><el-descriptions :column="1" border><el-descriptions-item label="环境">{{environmentLabel}}</el-descriptions-item><el-descriptions-item label="启用版本">{{selected.activeVersion||'未启用'}}</el-descriptions-item><el-descriptions-item label="部署">{{selected.binding?.deploymentId||'--'}}</el-descriptions-item><el-descriptions-item label="绑定">{{selected.binding?.endpointRef||'--'}}</el-descriptions-item></el-descriptions><div v-if="data?.canManage" class="form-actions"><el-button v-if="selected.active" type="danger" :disabled="busy" @click="activate(selected,true)">停用服务</el-button><el-button type="primary" :disabled="busy||selected.manifest.exposure==='catalog'||['deprecated','retired'].includes(selected.lifecycle?.status||'')" @click="activate(selected)">{{selected.manifest.exposure==='catalog'?'目录管理接口':data.bindingRequired?'发布部署':'启用此版本'}}</el-button></div></template>
    <template v-else><el-table :data="data?.audit.filter(a=>a.serviceId===selected?.manifest.serviceId)||[]" empty-text="暂无变更"><el-table-column label="时间" width="180"><template #default="{row}">{{dateTime(row.at)}}</template></el-table-column><el-table-column label="操作" width="110"><template #default="{row}">{{({publish:'登记版本',activate:'环境发布',disable:'停用服务',lifecycle:'生命周期'} as Record<string,string>)[row.action]||row.action}}</template></el-table-column><el-table-column prop="version" label="版本" width="95"/><el-table-column label="变更内容" min-width="260"><template #default="{row}">{{row.lifecycle?.reason||row.binding?.deploymentId||'--'}}</template></el-table-column></el-table><el-table :data="workspace?.events?.filter(e=>e.serviceId===selected?.manifest.serviceId)||[]" empty-text="暂无分类变更"><el-table-column label="时间" width="180"><template #default="{row}">{{dateTime(row.at)}}</template></el-table-column><el-table-column label="目录变更" min-width="220"><template #default="{row}">{{categoryName(row.before?.category)}} → {{categoryName(row.after?.category)}} · {{row.after?.owner||'未设置负责人'}}</template></el-table-column></el-table></template>
   </template>
  </el-drawer>
 </ConfiguredApplicationShell>
</template>
