<script setup lang="ts">
import {computed,ref,watch,onUnmounted} from 'vue';
import {Plus,Delete,Upload,Edit,ArrowLeft} from '@element-plus/icons-vue';
import {ElMessage,ElMessageBox} from 'element-plus';
import {client} from './api';
import {emptyRegistration,newOperation,fromPublication,buildRegistration,type OperationDraft} from './registration';
import type {Publication,Catalog} from './models';
const props=defineProps<{source?:Publication|null;data:Catalog;environment:string}>();const emit=defineEmits<{saved:[];cancel:[];state:[dirty:boolean,busy:boolean]}>();
const form=ref(props.source?fromPublication(props.source.manifest,props.source.contract):emptyRegistration());
if(props.source){const parts=form.value.version.split('.').map(Number);parts[2]++;form.value.version=parts.join('.');}
const mode=ref('form'),manifestText=ref(''),contractText=ref(''),initial=JSON.stringify(form.value),saving=ref(false),fileInput=ref<HTMLInputElement|null>(null),editing=ref<number|null>(null),operationDraft=ref<OperationDraft|null>(null),operationInitial=ref('');
const operationChanged=computed(()=>!!operationDraft.value&&JSON.stringify(operationDraft.value)!==operationInitial.value);
const committed=ref(false);
const dirty=computed(()=>!committed.value&&(JSON.stringify(form.value)!==initial||!!manifestText.value.trim()||!!contractText.value.trim()||operationChanged.value));
watch([dirty,saving],()=>emit('state',dirty.value,saving.value),{immediate:true});onUnmounted(()=>emit('state',false,false));
watch(()=>form.value.appId,(value,previous)=>{if(!props.source&&(!form.value.serviceId||form.value.serviceId===previous+'.api'))form.value.serviceId=value+'.api';});
function editOperation(index:number){editing.value=index;operationDraft.value=JSON.parse(JSON.stringify(index<0?newOperation():form.value.operations[index]));operationInitial.value=JSON.stringify(operationDraft.value);}
function addParameter(){operationDraft.value?.parameters.push({name:'',in:'query',required:false,description:'',schema:JSON.stringify({type:'string'})});}
async function closeOperation(done?:()=>void){if(operationChanged.value){try{await ElMessageBox.confirm('放弃尚未保存的 API 更改？','未提交更改',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'});}catch{return;}}operationDraft.value=null;done?.();}
function saveOperation(){const op=operationDraft.value;if(!op)return;try{buildRegistration({...form.value,name:form.value.name||'校验',appId:form.value.appId||'validation',serviceId:form.value.serviceId||'validation.api',operations:[op]});if(editing.value===-1)form.value.operations.push(op);else form.value.operations[editing.value!]=op;operationDraft.value=null;}catch(e){ElMessage.error((e as Error).message);}}
async function removeOperation(index:number){try{await ElMessageBox.confirm('从当前草稿移除此 API？','移除 API',{confirmButtonText:'移除',cancelButtonText:'取消'});form.value.operations.splice(index,1);}catch{}}
async function importFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{if(file.size>600*1024)throw Error('登记包不能超过 600 KiB');const value=JSON.parse(await file.text());if(!value.manifest||!Array.isArray(value.manifest.operations))throw Error('登记包缺少服务清单');if(dirty.value)await ElMessageBox.confirm('用导入内容替换当前草稿？','导入登记包',{confirmButtonText:'替换',cancelButtonText:'取消'});form.value=fromPublication(value.manifest,value.contract);manifestText.value=JSON.stringify(value.manifest,null,2);contractText.value=value.contract?JSON.stringify(value.contract,null,2):'';mode.value='form';ElMessage.success('登记包已载入');}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message);}finally{(event.target as HTMLInputElement).value='';}}
function switchMode(value:string){try{if(value==='json'){const registration=buildRegistration(form.value);manifestText.value=JSON.stringify(registration.manifest,null,2);contractText.value=JSON.stringify(registration.contract,null,2);}else if(manifestText.value.trim()){form.value=fromPublication(JSON.parse(manifestText.value),contractText.value.trim()?JSON.parse(contractText.value):undefined);}mode.value=value;}catch(error){ElMessage.error((error as Error).message);}}
async function submit(){if(saving.value)return;try{const registration=mode.value==='form'?buildRegistration(form.value):{manifest:JSON.parse(manifestText.value),...(contractText.value.trim()?{contract:JSON.parse(contractText.value)}:{})};saving.value=true;await client.request('/publications?environment='+encodeURIComponent(props.environment),{method:'POST',body:JSON.stringify(registration)});committed.value=true;saving.value=false;emit('state',false,false);ElMessage.success('服务版本已登记');emit('saved');}catch(error){ElMessage.error((error as Error).message);}finally{saving.value=false;}}
</script>
<template>
 <section v-if="data.canManage" class="registration-page">
  <div class="service-toolbar"><el-radio-group :model-value="mode" @change="switchMode(String($event))"><el-radio-button value="form">可视化配置</el-radio-button><el-radio-button value="json">清单与契约</el-radio-button></el-radio-group><el-button :icon="Upload" :disabled="saving" @click="fileInput?.click()">导入登记包</el-button><input ref="fileInput" type="file" accept=".json,application/json" hidden @change="importFile"/></div>
  <el-form v-if="mode==='form'" label-position="top" :disabled="saving"><h3>基本信息</h3><div class="form-grid"><el-form-item label="服务名称" required><el-input v-model="form.name" maxlength="100" aria-label="服务名称"/></el-form-item><el-form-item label="提供应用" required><el-select v-model="form.appId" :disabled="!!source" aria-label="提供应用选择"><el-option v-for="app in data.providers||[]" :key="app.id" :value="app.id" :label="app.name"/></el-select></el-form-item><el-form-item label="服务标识" required><el-input v-model="form.serviceId" :disabled="!!source" aria-label="服务标识" :placeholder="form.appId?form.appId+'.api':''"/></el-form-item><el-form-item label="版本" required><el-input v-model="form.version" aria-label="服务版本" placeholder="1.0.0"/></el-form-item></div><el-form-item label="服务描述"><el-input v-model="form.description" type="textarea" :rows="3" maxlength="2000" aria-label="服务描述"/></el-form-item><div class="service-toolbar"><h3>API 接口</h3><el-button :icon="Plus" @click="editOperation(-1)">新增 API</el-button></div><el-table :data="form.operations" empty-text="暂无 API"><el-table-column prop="summary" label="API 名称" min-width="160"/><el-table-column prop="operationId" label="操作标识" min-width="130"/><el-table-column prop="method" label="方法" width="90"/><el-table-column prop="path" label="路径" min-width="200"/><el-table-column label="操作" width="120"><template #default="{$index}"><el-tooltip content="编辑 API"><el-button text circle :icon="Edit" aria-label="编辑 API" @click="editOperation($index)"/></el-tooltip><el-tooltip content="移除 API"><el-button text circle :icon="Delete" aria-label="移除 API" @click="removeOperation($index)"/></el-tooltip></template></el-table-column></el-table></el-form>
  <el-form v-else label-position="top" :disabled="saving"><el-form-item label="服务清单"><el-input v-model="manifestText" type="textarea" :rows="15" aria-label="应用服务清单"/></el-form-item><el-form-item label="OpenAPI 契约"><el-input v-model="contractText" type="textarea" :rows="18" aria-label="OpenAPI 契约"/></el-form-item></el-form>
  <div class="form-actions"><el-button :icon="ArrowLeft" :disabled="saving" @click="emit('cancel')">返回目录</el-button><el-button type="primary" :loading="saving" @click="submit">校验并登记版本</el-button></div>
 </section>
 <el-empty v-else description="当前账号没有服务维护权限"/>
 <el-dialog :model-value="!!operationDraft" :title="editing===-1?'新增 API':'编辑 API'" width="min(920px,94vw)" :before-close="closeOperation" :close-on-click-modal="false">
  <el-form v-if="operationDraft" label-position="top"><div class="form-grid"><el-form-item label="API 名称" required><el-input v-model="operationDraft.summary" maxlength="200" aria-label="API 名称"/></el-form-item><el-form-item label="操作标识" required><el-input v-model="operationDraft.operationId" maxlength="80" aria-label="API 操作标识"/></el-form-item><el-form-item label="请求方法" required><el-select v-model="operationDraft.method" aria-label="API 请求方法"><el-option v-for="method in ['GET','POST','PUT','PATCH','DELETE']" :key="method" :value="method" :label="method"/></el-select></el-form-item><el-form-item label="接口路径" required><el-input v-model="operationDraft.path" aria-label="API 路径" placeholder="/entries/{id}"/></el-form-item></div>
   <div class="service-toolbar"><h3>请求参数</h3><el-button :icon="Plus" @click="addParameter">添加参数</el-button></div>
   <div v-for="(parameter,index) in operationDraft.parameters" :key="index" class="parameter-row"><template v-if="parameter.original?.$ref"><code>{{parameter.original.$ref}}</code></template><template v-else><el-input v-model="parameter.name" aria-label="参数名称" placeholder="参数名称"/><el-select v-model="parameter.in" aria-label="参数位置"><el-option v-for="location in [{id:'query',name:'Query'},{id:'header',name:'Header'},{id:'path',name:'Path'},{id:'cookie',name:'Cookie'}]" :key="location.id" :value="location.id" :label="location.name"/></el-select><el-checkbox v-model="parameter.required" :disabled="parameter.in==='path'">必填</el-checkbox><el-input v-model="parameter.description" aria-label="参数说明" placeholder="参数说明"/><el-input v-model="parameter.schema" aria-label="参数 Schema" placeholder="JSON Schema"/></template><el-button :icon="Delete" text circle aria-label="移除参数" @click="operationDraft.parameters.splice(index,1)"/></div>
   <el-form-item label="请求正文定义（OpenAPI requestBody）"><el-input v-model="operationDraft.requestBody" type="textarea" :rows="5" aria-label="请求正文定义"/></el-form-item><el-form-item label="响应与错误定义（OpenAPI responses）" required><el-input v-model="operationDraft.responses" type="textarea" :rows="8" aria-label="响应与错误定义"/></el-form-item>
  </el-form>
  <template #footer><el-button @click="closeOperation()">取消</el-button><el-button type="primary" @click="saveOperation">保存到草稿</el-button></template>
 </el-dialog>
</template>
