<script setup lang="ts">
import {computed,onUnmounted,ref,watch} from 'vue';
import {Refresh,Search} from '@element-plus/icons-vue';
import {client} from './api';
import ApiGovernance from './ApiGovernance.vue';
import {bytes,dateTime,serviceRows,type Catalog} from './models';
interface Metric {count:number;successful:number;failed:number;cancelled:number;unknown:number;averageMs:number;responseBytes:number|null;measured:number;successRate:number|null}
interface Insights {summary:Metric;groups:Array<Metric&{serviceId:string;operationId:string}>;series:Array<Metric&{at:string}>;logs:Array<{id:string;at:string;serviceId:string;operationId:string;status:number;outcome:string;durationMs:number;responseBytes?:number;requestId?:string;path?:string;version?:string}>;total:number;pageSize:number;coverage:string;from:string;to:string;collector?:{pending:number;droppedSinceStart:number}}
const props=defineProps<{data:Catalog;environment:string;serviceId?:string;operationId?:string}>();
const view=ref(props.serviceId?'logs':'services'),period=ref(24),service=ref(props.serviceId||''),operation=ref(props.operationId||''),outcome=ref(''),page=ref(1),loading=ref(false),error=ref(''),data=ref<Insights|null>(null);
const range=ref<[Date,Date]>([new Date(Date.now()-86400000),new Date()]);let run=0,controller:AbortController|undefined;
const rows=computed(()=>serviceRows(props.data.items));
const serviceName=(id:string)=>rows.value.find(p=>p.manifest.serviceId===id)?.manifest.name||id;
const operationName=(serviceId:string,operationId:string)=>props.data.items.find(p=>p.manifest.serviceId===serviceId&&p.manifest.operations.some(o=>o.operationId===operationId))?.manifest.operations.find(o=>o.operationId===operationId)?.summary||operationId;
const empty=():Metric=>({count:0,successful:0,failed:0,cancelled:0,unknown:0,averageMs:0,responseBytes:null,measured:0,successRate:null});
function combine(values:Metric[]){const result=empty();let duration=0;for(const value of values){result.count+=value.count;result.successful+=value.successful;result.failed+=value.failed;result.cancelled+=value.cancelled;result.unknown+=value.unknown;duration+=value.averageMs*value.count;result.measured+=value.measured;if(value.responseBytes!=null)result.responseBytes=(result.responseBytes||0)+value.responseBytes;}result.averageMs=result.count?duration/result.count:0;result.successRate=result.count>result.unknown?100*result.successful/(result.count-result.unknown):null;return result;}
const serviceStats=computed(()=>rows.value.filter(p=>!service.value||p.manifest.serviceId===service.value).map(p=>({...combine(data.value?.groups.filter(g=>g.serviceId===p.manifest.serviceId)||[]),id:p.manifest.serviceId,name:p.manifest.name,active:p.active,apiCount:p.manifest.operations.length})));
const apiStats=computed(()=>data.value?.groups.map(g=>({...g,name:operationName(g.serviceId,g.operationId),service:serviceName(g.serviceId)}))||[]);
const series=computed(()=>data.value?.series||[]),maxCount=computed(()=>Math.max(1,...series.value.map(s=>s.count))),maxDuration=computed(()=>Math.max(1,...series.value.map(s=>s.averageMs)));
async function load(){const current=++run;controller?.abort();controller=new AbortController();loading.value=true;error.value='';try{if(!range.value?.[0]||!range.value?.[1])throw Error('请选择起止时间');const params=new URLSearchParams({environment:props.environment,from:range.value[0].toISOString(),to:range.value[1].toISOString(),serviceId:service.value,operationId:operation.value,outcome:outcome.value,page:String(page.value)});const result=await client.request<Insights>('/insights?'+params,{signal:controller.signal});if(current===run)data.value=result;}catch(e){if(current===run&&(e as Error).name!=='AbortError'){error.value=(e as Error).message;data.value=null;}}finally{if(current===run)loading.value=false;}}
function refresh(){if(period.value)range.value=[new Date(Date.now()-period.value*3600000),new Date()];void load();}
function drill(serviceId:string,operationId=''){service.value=serviceId;operation.value=operationId;view.value='logs';page.value=1;}
watch(period,()=>{if(period.value){range.value=[new Date(Date.now()-period.value*3600000),new Date()];page.value=1;void load();}});
watch([service,operation,outcome,()=>props.environment],()=>{if(page.value!==1)page.value=1;else void load();});watch(page,()=>void load());
watch([()=>props.serviceId,()=>props.operationId],([value,op])=>{service.value=value||'';operation.value=op||'';view.value=value?'logs':'services';});
onUnmounted(()=>{run++;controller?.abort();});void load();
const outcomeLabel=(value:string)=>({success:'成功',error:'失败',cancelled:'已取消',unknown:'历史未分类'}[value]||'未知');
</script>
<template>
 <div class="service-toolbar">
  <el-select v-model="service" placeholder="全部服务" clearable aria-label="统计服务" class="service-provider" @change="operation='' "><el-option v-for="p in rows" :key="p.manifest.serviceId" :value="p.manifest.serviceId" :label="p.manifest.name"/></el-select>
  <el-select v-model="period" aria-label="统计时间范围" class="service-status"><el-option v-for="p in [{value:0.5,label:'最近30分钟'},{value:6,label:'最近6小时'},{value:24,label:'最近24小时'},{value:168,label:'最近7天'},{value:720,label:'最近30天'},{value:0,label:'自定义'}]" :key="p.value" :value="p.value" :label="p.label"/></el-select>
  <el-date-picker v-if="period===0" v-model="range" type="datetimerange" start-placeholder="开始时间" end-placeholder="结束时间" aria-label="自定义统计时间" @change="page=1;load()"/>
  <el-tooltip content="刷新统计"><el-button :icon="Refresh" circle aria-label="刷新统计" :loading="loading" @click="refresh"/></el-tooltip>
 </div>
 <el-alert v-if="error" type="error" :title="error" show-icon :closable="false"/>
 <el-skeleton v-if="loading&&!data" :rows="7" animated/>
 <template v-if="data">
  <div class="metrics-band"><div><span>已登记服务</span><strong>{{rows.length}}</strong></div><div><span>已登记操作</span><strong>{{rows.reduce((sum,row)=>sum+row.manifest.operations.length,0)}}</strong></div><div><span>调用次数</span><strong>{{data.summary.count.toLocaleString()}}</strong></div><div><span>成功率</span><strong>{{data.summary.successRate==null?'--':data.summary.successRate.toFixed(1)+'%'}}</strong></div><div><span>失败 / 取消</span><strong>{{data.summary.failed}} / {{data.summary.cancelled}}</strong></div></div>
  <div class="observation-caption"><span>{{dateTime(data.from)}} 至 {{dateTime(data.to)}}</span><span>{{data.coverage==='persisted'?'持久化调用记录':'最近 300 条记录窗口'}} · 历史未分类 {{data.summary.unknown}} 条 · 流量覆盖 {{data.summary.measured}} / {{data.summary.count}}</span></div>
  <el-alert v-if="data.coverage!=='persisted'||data.collector?.droppedSinceStart" type="warning" :closable="false" :title="data.coverage!=='persisted'?'当前为本地记录窗口，统计不代表完整时间范围。':'当前实例启动后有 '+data.collector?.droppedSinceStart+' 条记录未落盘，统计存在缺口。'"/>
  <el-tabs v-model="view"><el-tab-pane name="services" label="服务统计"/><el-tab-pane name="apis" label="API 统计"/><el-tab-pane name="charts" label="图表分析"/><el-tab-pane name="logs" label="调用日志"/><el-tab-pane v-if="props.data.canManage" name="governance" label="API 治理"/></el-tabs>
  <ApiGovernance v-if="view==='governance'&&props.data.canManage" :environment="environment"/>
  <el-table v-else-if="view==='services'" :data="serviceStats" empty-text="暂无服务" v-loading="loading"><el-table-column prop="name" label="服务名称" min-width="180"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.active?'success':'info'">{{row.active?'已启用':'未启用'}}</el-tag></template></el-table-column><el-table-column prop="apiCount" label="API 数" width="80"/><el-table-column prop="count" label="调用次数" width="100"/><el-table-column label="成功率" width="100"><template #default="{row}">{{row.successRate==null?'--':row.successRate.toFixed(1)+'%'}}</template></el-table-column><el-table-column label="平均耗时" width="120"><template #default="{row}">{{row.count?row.averageMs.toFixed(0)+' ms':'--'}}</template></el-table-column><el-table-column label="响应流量" width="120"><template #default="{row}">{{bytes(row.responseBytes)}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button link type="primary" @click="drill(row.id)">调用日志</el-button></template></el-table-column></el-table>
  <el-table v-else-if="view==='apis'" :data="apiStats" empty-text="所选时间内暂无调用"><el-table-column label="API" min-width="220"><template #default="{row}">{{row.name}}<div class="secondary">{{row.operationId}}</div></template></el-table-column><el-table-column prop="service" label="所属服务" min-width="140"/><el-table-column prop="count" label="调用次数" width="100"/><el-table-column prop="failed" label="失败次数" width="100"/><el-table-column label="平均耗时" width="110"><template #default="{row}">{{row.averageMs.toFixed(0)}} ms</template></el-table-column><el-table-column label="响应流量" width="120"><template #default="{row}">{{bytes(row.responseBytes)}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button link type="primary" @click="drill(row.serviceId,row.operationId)">调用日志</el-button></template></el-table-column></el-table>
  <template v-else-if="view==='charts'"><el-empty v-if="!series.length" description="所选时间内暂无调用"/><div v-else class="metric-charts"><section><h3>调用次数</h3><div class="metric-bars" role="img" aria-label="按时间统计的调用次数"><el-tooltip v-for="item in series" :key="item.at" :content="dateTime(item.at)+' · '+item.count+' 次'"><div class="metric-column"><span :style="{height:Math.max(2,item.count/maxCount*180)+'px'}"/><small>{{new Date(item.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></div></el-tooltip></div></section><section><h3>平均响应时长</h3><div class="metric-bars duration" role="img" aria-label="按时间统计的平均响应时长"><el-tooltip v-for="item in series" :key="item.at" :content="dateTime(item.at)+' · '+item.averageMs.toFixed(0)+' ms'"><div class="metric-column"><span :style="{height:Math.max(2,item.averageMs/maxDuration*180)+'px'}"/><small>{{new Date(item.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></div></el-tooltip></div></section></div></template>
  <template v-else><div class="service-toolbar"><el-input v-model="operation" aria-label="操作标识筛选" placeholder="操作标识" clearable class="service-search" :prefix-icon="Search"/><el-select v-model="outcome" placeholder="全部结果" clearable aria-label="调用结果" class="service-status"><el-option v-for="value in ['success','error','cancelled','unknown']" :key="value" :value="value" :label="outcomeLabel(value)"/></el-select></div><el-table :data="data.logs" empty-text="没有符合条件的调用记录" v-loading="loading"><el-table-column label="调用时间" width="185"><template #default="{row}">{{dateTime(row.at)}}</template></el-table-column><el-table-column label="服务 / API" min-width="230"><template #default="{row}">{{operationName(row.serviceId,row.operationId)}}<div class="secondary">{{serviceName(row.serviceId)}} · {{row.version||'历史版本'}}</div></template></el-table-column><el-table-column label="结果" width="110"><template #default="{row}"><el-tag :type="row.outcome==='success'?'success':row.outcome==='error'?'danger':'info'" size="small">{{outcomeLabel(row.outcome)}}</el-tag></template></el-table-column><el-table-column prop="status" label="HTTP" width="80"/><el-table-column label="耗时" width="100"><template #default="{row}">{{row.durationMs}} ms</template></el-table-column><el-table-column label="响应流量" width="120"><template #default="{row}">{{bytes(row.responseBytes)}}</template></el-table-column><el-table-column prop="requestId" label="请求标识" min-width="200" show-overflow-tooltip/></el-table><div class="service-pagination"><el-pagination v-model:current-page="page" :page-size="data.pageSize" :total="data.total" layout="total, prev, pager, next"/></div></template>
 </template>
</template>
