import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
const require=createRequire(new URL('../../mg-desktop-one/package.json',import.meta.url));
const {chromium}=require('playwright');
const config=JSON.parse(await readFile('server/resources.json','utf8')),state=JSON.parse(await readFile('.runtime/data/state.json','utf8'));
const data={pools:config.pools,resources:config.resources.map(({credential,...r})=>({...r,observation:state.observations[r.id],stale:false,collecting:false})),audit:state.audit.slice().reverse(),cloudApiConfigured:false};
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**',async route=>{const p=new URL(route.request().url()).pathname;if(p.endsWith('/overview'))return route.fulfill({json:data});if(p==='/api/session')return route.fulfill({json:{user:{name:'验证账户'},csrfToken:'ui-only'}});return route.fulfill({status:404,json:{message:'未配置测试接口'}})});
await page.goto('http://127.0.0.1:14371/pools');await page.getByRole('heading',{name:'平台生产资源池'}).waitFor();
await mkdir('.runtime/ui',{recursive:true});await page.screenshot({path:'.runtime/ui/pools.png',fullPage:true});
await page.getByRole('button',{name:/平台生产服务器/}).click();await page.getByRole('heading',{name:'平台生产服务器 · 资源详情'}).waitFor();
await page.getByRole('button',{name:'编辑资料'}).first().click();await page.getByLabel('负责人',{exact:true}).fill('UI 验证');await page.getByRole('button',{name:'取消',exact:true}).click();
await page.screenshot({path:'.runtime/ui/servers.png',fullPage:true});
await page.goto('http://127.0.0.1:14371/deployments');await page.getByRole('heading',{name:'Token One 控制台',exact:true}).waitFor();
await page.setViewportSize({width:600,height:800});await page.screenshot({path:'.runtime/ui/narrow.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await writeFile('.runtime/ui/result.json',JSON.stringify({errors,horizontalOverflow:overflow,source:'真实 SSH 快照；仅 UI 验证通过拦截传输加载，真实认证另由服务端测试验证'},null,2));
await browser.close();if(errors.length||overflow)throw new Error(JSON.stringify({errors,overflow}));console.log('UI 页面、详情编辑/取消、窄屏检查通过；无运行时异常。');
