import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer, type Server } from 'node:http';
import { mkdtemp, readFile, readdir, rm, rename, mkdir } from 'node:fs/promises';
import { Readable } from 'node:stream';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { FilesStore } from '../server/store.ts';
import { createFilesServer } from '../server/http.ts';
import { UnifiedIdentityClient } from '../server/unified-client.ts';
async function listen(server: Server) { await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); return `http://127.0.0.1:${(server.address() as {port:number}).port}`; }
async function close(server: Server) { server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); }
test('真实 HTTP 两用户隔离、受保护桌面、文件生命周期与并发配额', async t => {
  const dir = await mkdtemp(join(tmpdir(), 'mg-files-test-'));
  let issuer = ''; const tokenA = 'a'.repeat(43), tokenB = 'b'.repeat(43); let introspections = 0;
  const auth = createServer(async (req,res) => { let raw='';for await(const chunk of req)raw+=chunk;res.setHeader('Content-Type','application/json'); if(req.url==='/token'){res.end(JSON.stringify({access_token:'machine-test',expires_in:60}));return;} assert.equal(req.headers.authorization,'Bearer machine-test');const body=JSON.parse(raw);assert(['files','office-one'].includes(body.app_id));introspections++;if(![tokenA,tokenB].includes(body.token)){res.end('{"active":false}');return;}const sub=body.token===tokenA?'owner-a':'owner-b';res.end(JSON.stringify({active:true,iss:issuer,aud:body.app_id,sub,sid:'session-'+sub,name:sub,username:sub,department:null,localUserId:null,role:'user',securityVersion:1,authTime:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600,amr:['pwd'],csrfToken:'csrf-'+sub})); });
  issuer=await listen(auth); const store=new FilesStore(dir,64,100);await store.initialize();const api=createFilesServer(store,new UnifiedIdentityClient({issuer,clientId:'files-service-test',clientSecret:'s'.repeat(32)}));const base=await listen(api);
  t.after(async()=>{await close(api);await close(auth);await rm(dir,{recursive:true,force:true});});
  async function call(path:string,method='GET',body?:unknown,owner='a',csrf=true) { const headers:Record<string,string>={Authorization:`Bearer ${owner==='a'?tokenA:tokenB}`};if(csrf)headers['X-CSRF-Token']='csrf-owner-'+owner;if(typeof body==='object'&&!(body instanceof Buffer))headers['Content-Type']='application/json'; const response=await fetch(base+'/api'+path,{method,headers,body:body===undefined?undefined:body instanceof Buffer?new Uint8Array(body):JSON.stringify(body)});return {status:response.status,body:response.headers.get('content-type')?.includes('json')?await response.json():await response.text(),headers:response.headers}; }
  const a=(await call('/entries')).body,b=(await call('/entries','GET',undefined,'b')).body;
  assert.notEqual(a.rootId,b.rootId);assert.equal(a.items.length,1);assert.equal(a.items[0].protected,'desktop');const desktop=a.desktopFolderId;
  await t.test('Office 最近打开按账户隔离、按打开时间排序且排除回收站',async()=>{
    const first=await store.upload('owner-b',b.rootId,'first.docx',1,Readable.from('1'));
    const second=await store.upload('owner-b',b.rootId,'second.xlsx',1,Readable.from('2'));
    const unopened=await store.upload('owner-b',b.rootId,'unopened.pptx',1,Readable.from('3'));
    try{
      assert.equal((await call('/office/documents?view=recent','GET',undefined,'b')).body.items.length,0);
      await store.access('owner-b',first.id,true);await store.access('owner-b',second.id,true);
      await store.transaction(()=>{store.get('owner-b',first.id).officeAccessedAt='2026-01-01T00:00:00.000Z';store.get('owner-b',second.id).officeAccessedAt='2026-01-02T00:00:00.000Z'});
      assert.deepEqual((await call('/office/documents?view=recent','GET',undefined,'b')).body.items.map((e:any)=>e.id),[second.id,first.id]);
      assert.equal((await call('/office/documents?view=recent')).body.items.length,0);
      assert.equal((await call('/office/documents?view=all','GET',undefined,'b')).body.items.length,3);
      assert.equal((await call('/office/documents?view=invalid')).status,400);
      await store.remove('owner-b',second.id);assert.deepEqual((await call('/office/documents?view=recent','GET',undefined,'b')).body.items.map((e:any)=>e.id),[first.id]);
    }finally{for(const file of [first,second,unopened]){if(!store.get('owner-b',file.id,true).deletedAt)await store.remove('owner-b',file.id);await store.permanent('owner-b',file.id)}}
  });
  await t.test('受保护目录和 CSRF',async()=>{for(const [method,path,body] of [['PATCH',`/entries/${desktop}`,{name:'其他'}],['POST',`/entries/${desktop}/move`,{parentId:a.rootId}],['DELETE',`/entries/${desktop}`,{}]] as const)assert.equal((await call(path,method,body)).status,403);assert.equal((await call('/folders','POST',{parentId:a.rootId,name:'失败'},'a',false)).status,403);assert.equal((await call('/folders','POST',{parentId:a.rootId,name:'../escape'})).status,400);});
  const folder=(await call('/folders','POST',{parentId:a.rootId,name:'文档'})).body;const child=(await call('/folders','POST',{parentId:folder.id,name:'子目录'})).body;
  await t.test('越权访问与循环移动',async()=>{assert.equal((await call(`/entries/${folder.id}`,'GET',undefined,'b')).status,404);assert.equal((await call(`/entries/${folder.id}`,'PATCH',{name:'入侵'},'b')).status,404);assert.equal((await call(`/entries/${folder.id}/move`,'POST',{parentId:child.id})).status,400);assert.equal((await call(`/entries/${folder.id}/move`,'POST',{parentId:b.rootId})).status,404);assert.equal((await call(`/uploads?parentId=${folder.id}&name=x.txt`,'POST',Buffer.from('x'),'b')).status,404);});
  const uploaded=await call(`/uploads?parentId=${folder.id}&name=${encodeURIComponent('说明 你好.txt')}`,'POST',Buffer.from('hello'));assert.equal(uploaded.status,201);const file=uploaded.body;
  await t.test('安全下载与名称处理',async()=>{assert.equal(file.preview,'text');const download=await call(`/entries/${file.id}/content`);assert.equal(download.body,'hello');assert.equal(download.headers.get('x-content-type-options'),'nosniff');assert.match(download.headers.get('content-disposition')||'',/^attachment;.*filename\*=UTF-8''/);assert.equal((await call(`/entries/${file.id}/content`,'GET',undefined,'b')).status,404);assert.equal((await call(`/uploads?parentId=${folder.id}&name=..%2Fbad.txt`,'POST',Buffer.from('x'))).status,400);const unsafe=await call(`/uploads?parentId=${folder.id}&name=unsafe.svg`,'POST',Buffer.from('<svg onload="alert(1)"></svg>'));assert.equal(unsafe.body.preview,'none');assert.equal((await call(`/entries/${unsafe.body.id}/content`)).headers.get('content-type'),'application/octet-stream');});
  await t.test('版本冲突、收藏、最近和桌面搬入',async()=>{assert.equal((await call(`/entries/${file.id}`,'PATCH',{name:'新名.txt',version:99})).status,409);await call(`/entries/${file.id}`,'PATCH',{favorite:true,version:1});assert.equal((await call('/entries?view=favorites')).body.items[0].id,file.id);await call(`/entries/${file.id}/access`,'POST');assert.equal((await call('/entries?view=recent')).body.items[0].id,file.id);await call(`/entries/${file.id}/move`,'POST',{parentId:desktop});assert.equal((await call('/desktop')).body.items[0].id,file.id);});
  await t.test('整树回收恢复、永删释放配额',async()=>{assert.equal((await call(`/entries/${folder.id}`,'DELETE')).status,200);assert.equal((await call(`/entries/${child.id}`)).status,404);assert.equal((await call('/entries?view=trash')).body.items.length,1);assert.ok((await call('/desktop')).body.trashCount>0);assert.equal((await call('/desktop','GET',undefined,'b')).body.trashCount,0);assert.equal((await call(`/entries/${folder.id}/restore`,'POST')).status,200);assert.equal((await call(`/entries/${child.id}`)).status,200);await call(`/entries/${folder.id}`,'DELETE');const before=(await call('/entries')).body.quota.used;await call(`/entries/${folder.id}/permanent`,'DELETE');assert.ok((await call('/entries')).body.quota.used<before);assert.equal((await call('/desktop')).body.trashCount,0);assert.equal((await call(`/entries/${child.id}`)).status,404);});
  await t.test('大小与并发配额',async()=>{assert.equal((await call(`/uploads?parentId=${a.rootId}&name=too-big.txt`,'POST',Buffer.alloc(65))).status,413);const results=await Promise.all([call(`/uploads?parentId=${a.rootId}&name=one.bin`,'POST',Buffer.alloc(60)),call(`/uploads?parentId=${a.rootId}&name=two.bin`,'POST',Buffer.alloc(60))]);assert.deepEqual(results.map(r=>r.status).sort(),[201,413]);assert.ok((await call('/entries')).body.quota.used<=100);});
  await t.test('元数据重新加载与安全对象键',async()=>{const loaded=new FilesStore(dir,64,100);await loaded.initialize();assert.equal(loaded.desktop('owner-a').id,desktop);assert.equal(loaded.usage('owner-a'),store.usage('owner-a'));const names=await readdir(join(dir,'objects'));assert.ok(names.every(name=>/^[0-9a-f-]{36}$/.test(name)));const metadata=JSON.parse(await readFile(join(dir,'metadata.json'),'utf8'));assert.ok(metadata.entries.every((e:any)=>e.ownerId==='owner-a'||e.ownerId==='owner-b'));assert.ok(introspections>30);});
  await t.test('元数据落盘故障后释放预留并允许重试',async()=>{const file=join(dir,'metadata.json'),backup=join(dir,'metadata.backup');await rename(file,backup);await mkdir(file);try{await assert.rejects(store.upload('owner-b',b.rootId,'failed.txt',10,Readable.from(Buffer.alloc(10))));assert.equal(store.reserved.get('owner-b')||0,0);assert.equal(store.usage('owner-b'),0);}finally{await rm(file,{recursive:true,force:true});await rename(backup,file);}const retry=await store.upload('owner-b',b.rootId,'retry.txt',10,Readable.from(Buffer.alloc(10)));assert.equal(retry.size,10);assert.equal(store.reserved.get('owner-b')||0,0);});
  await t.test('过期回收站页面不可永久删除新批次',async()=>{const folder=(await call('/folders','POST',{parentId:b.rootId,name:'版本保护'},'b')).body;await call(`/entries/${folder.id}`,'DELETE',{},'b');await call(`/entries/${folder.id}/restore`,'POST',{version:2},'b');const child=(await call(`/uploads?parentId=${folder.id}&name=new.txt`,'POST',Buffer.from('new'),'b')).body;await call(`/entries/${folder.id}`,'DELETE',{},'b');assert.equal((await call(`/entries/${folder.id}/permanent`,'DELETE',{version:2},'b')).status,409);assert.equal((await call(`/entries/${folder.id}/restore`,'POST',{version:2},'b')).status,409);assert.equal((await call(`/entries/${folder.id}/restore`,'POST',{version:4},'b')).status,200);assert.equal((await call(`/entries/${child.id}`,'GET',undefined,'b')).status,200);});
});
