import { chromium, expect } from '@playwright/test';
import { readFile, mkdir } from 'node:fs/promises';
expect.configure({timeout:20000});
const account=JSON.parse(await readFile('../mg-desktop-one/.runtime/local/account.json','utf8'));
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:980}});const page=await context.newPage();
await mkdir('.runtime/qa',{recursive:true});await context.addInitScript(()=>{window.__fileMessages=[];addEventListener('message',event=>{const m=event.data;if(m&&typeof m.type==='string'&&/dialog|navigate/.test(m.type))window.__fileMessages.push({type:m.type,dialogId:m.payload?.dialogId,outcome:m.payload?.outcome,message:m.payload?.message,path:m.type==='navigate'?m.payload?.path:undefined});});});const errors=[];page.on('pageerror',e=>errors.push(e.message.split('\n')[0]));
let stage='统一认证',folderId,desktopFileId,csrf;const name=`文件验证-${Date.now()}`;
function samplePdf(){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Count 1 /Kids [3 0 R] >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 180] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];const stream='BT /F1 18 Tf 30 100 Td (Files preview verified) Tj ET';objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);let text='%PDF-1.4\n';const offsets=[0];objects.forEach((obj,i)=>{offsets.push(text.length);text+=`${i+1} 0 obj\n${obj}\nendobj\n`;});const xref=text.length;text+=`xref\n0 6\n0000000000 65535 f \n`+offsets.slice(1).map(offset=>`${String(offset).padStart(10,'0')} 00000 n \n`).join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(text);}
try{
 await page.goto('http://127.0.0.1:14351/my-files');await page.getByRole('textbox',{name:'登录账号',exact:true}).fill(account.username);await page.getByRole('textbox',{name:'登录密码',exact:true}).fill(account.password);await page.getByRole('button',{name:'登 录',exact:true}).click();await page.waitForURL('http://127.0.0.1:14351/my-files');
 stage='独立文件页';await expect(page.locator('.finder-folder-title')).toBeVisible();await expect(page.locator('.app-header')).toBeVisible();await expect(page.getByText('可用',{exact:false})).toBeVisible();
 stage='新建文件夹';await page.getByRole('button',{name:'新建文件夹',exact:true}).click();await page.getByRole('textbox',{name:'名称',exact:true}).fill(name);const created=page.waitForResponse(r=>r.url().endsWith('/api/apps/files/folders')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存',exact:true}).click();const response=await created;expect(response.status()).toBe(201);folderId=(await response.json()).id;await expect(page.locator('.file-grid').getByText(name,{exact:true})).toBeVisible();await page.locator('.file-grid').getByText(name,{exact:true}).dblclick();await page.waitForURL(`http://127.0.0.1:14351/my-files/${folderId}`);
 stage='Uppy真实上传';await expect(page.getByRole('button',{name:'上传文件',exact:true})).toBeEnabled();const uploaded=page.waitForResponse(r=>r.url().includes('/api/apps/files/uploads?')&&r.request().method()==='POST');await page.locator('input[type=file]').setInputFiles({name:'预览验证.txt',mimeType:'text/plain',buffer:Buffer.from('安全的文本预览\n<script>alert(1)</script>')});expect((await uploaded).status()).toBe(201);await expect(page.locator('.file-grid').getByText('预览验证.txt',{exact:true})).toBeVisible();
 stage='文本预览';await page.locator('.file-grid').getByText('预览验证.txt',{exact:true}).dblclick();await expect(page.locator('.el-dialog pre')).toContainText('<script>alert(1)</script>');await page.screenshot({path:'.runtime/qa/browser-preview.png'});await page.locator('.el-dialog__headerbtn').click();await expect(page.locator('.el-overlay:visible')).toHaveCount(0);
 stage='图片和PDF预览';
 for(const fixture of [{name:'图片验证.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')},{name:'PDF验证.pdf',mimeType:'application/pdf',buffer:samplePdf()}]){
   await expect(page.getByRole('button',{name:'上传文件',exact:true})).toBeEnabled();const done=page.waitForResponse(r=>r.url().includes('/api/apps/files/uploads?')&&r.request().method()==='POST');await page.locator('input[type=file]').setInputFiles(fixture);expect((await done).status()).toBe(201);await page.locator('.file-grid').getByText(fixture.name,{exact:true}).dblclick();if(fixture.name.endsWith('.png'))await expect(page.locator('.preview-body img')).toBeVisible();else{await expect(page.locator('.preview-body canvas')).toHaveAttribute('width',/\d+/);await expect(page.locator('.pdf-controls')).toContainText('1 / 1');await page.screenshot({path:'.runtime/qa/pdf-preview.png'});}await page.locator('.el-dialog__headerbtn').click();await expect(page.locator('.el-overlay:visible')).toHaveCount(0);
 }
 stage='Finder视图切换';await page.getByRole('button',{name:'列表视图',exact:true}).click();await expect(page.locator('.finder-list tbody tr')).toHaveCount(3);await expect(page.locator('.finder-list th')).toHaveText(['名称','修改日期','大小','类型']);await page.screenshot({path:'.runtime/qa/finder-list.png'});await page.getByRole('button',{name:'图标视图',exact:true}).click();await page.screenshot({path:'.runtime/qa/finder-grid.png'});
 stage='右键和键盘菜单';await page.locator('.file-tile').first().click({button:'right'});await expect(page.getByRole('menuitem',{name:'重命名',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.finder-context-menu')).toHaveCount(0);await page.locator('.file-tile').first().focus();await page.keyboard.press('Shift+F10');await expect(page.getByRole('menuitem',{name:'下载',exact:true})).toBeVisible();await page.keyboard.press('Escape');const canvas=page.locator('.finder-content'),box=await canvas.boundingBox();await canvas.click({button:'right',position:{x:box.width-3,y:box.height-3}});await expect(page.getByRole('menuitem',{name:'新建文件夹',exact:true})).toBeVisible();const menu=await page.locator('.finder-context-menu').boundingBox();expect(menu.x+menu.width).toBeLessThanOrEqual(1440);expect(menu.y+menu.height).toBeLessThanOrEqual(980);await page.screenshot({path:'.runtime/qa/context-menu.png'});await page.keyboard.press('Escape');
 stage='浏览器桌面入口';await page.getByRole('button',{name:'桌面',exact:true}).click();await expect(page.locator('.finder-folder-title')).toHaveText('桌面');await page.goto('http://127.0.0.1:14351/my-files/desktop?intent=new-folder');await expect(page.getByRole('textbox',{name:'名称',exact:true})).toBeVisible();await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.locator('.el-overlay:visible')).toHaveCount(0);await page.goto('http://127.0.0.1:14351/my-files/desktop?intent=upload');await expect(page.getByRole('button',{name:'选择文件',exact:true})).toBeVisible();await page.getByRole('button',{name:'取消',exact:true}).click();await page.goto(`http://127.0.0.1:14351/my-files/${folderId}`);await expect(page.locator('.file-tile')).toHaveCount(3);
 stage='窄屏列表';await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.runtime/qa/mobile-files.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.setViewportSize({width:1440,height:980});
 stage='桌面注册弹窗';await page.goto(`http://127.0.0.1:4301/open?app=files&path=${encodeURIComponent('/my-files/'+folderId)}`);const app=page.frameLocator('iframe[title="文件"]:not([src*="platformDialog="])');await expect(app.locator('.finder-folder-title')).toBeVisible();await expect(app.locator('.app-header')).toBeHidden();await app.getByRole('button',{name:'新建文件夹',exact:true}).click();const dialog=page.frameLocator('iframe[src*="platformDialog=file-name"]');await expect(dialog.getByRole('textbox',{name:'名称',exact:true})).toBeVisible();await expect(dialog.locator('.app-header')).toHaveCount(0);await dialog.getByRole('textbox',{name:'名称',exact:true}).fill('不保存的关闭保护测试');await dialog.getByRole('button',{name:'取消',exact:true}).click();await expect(dialog.getByRole('button',{name:'放弃',exact:true})).toBeVisible();await dialog.getByRole('button',{name:'放弃',exact:true}).click();await expect(page.locator('iframe[src*="platformDialog=file-name"]')).toHaveCount(0);await page.screenshot({path:'.runtime/qa/desktop-files.png'});
 stage='桌面目录联动';await app.getByRole('button',{name:'桌面',exact:true}).click();await expect(app.locator('.finder-folder-title')).toHaveText('桌面');await expect(app.getByRole('button',{name:'上传文件',exact:true})).toBeEnabled();const desktopUpload=page.waitForResponse(r=>r.url().includes('/api/apps/files/uploads?')&&r.request().method()==='POST');const desktopName=`桌面联动验证-${Date.now()}.txt`;await app.locator('input[type=file]').setInputFiles({name:desktopName,mimeType:'text/plain',buffer:Buffer.from('桌面文件双击验证')});const desktopResult=await desktopUpload;expect(desktopResult.status()).toBe(201);desktopFileId=(await desktopResult.json()).id;const started=Date.now();await expect(page.getByRole('button',{name:`${desktopName}（文件）`,exact:true})).toBeVisible({timeout:17000});const refreshMs=Date.now()-started;await page.locator('.app-window').filter({has:page.locator('iframe[title="文件"]:not([src*="platformDialog="])')}).locator('.window-minimize').click();await page.getByRole('button',{name:`${desktopName}（文件）`,exact:true}).dblclick();await expect(page.frameLocator('iframe[src*="platformDialog=file-preview"]').locator('pre')).toContainText('桌面文件双击验证');console.log(JSON.stringify({desktopRefreshMs:refreshMs}));
 expect(errors).toEqual([]);console.log(JSON.stringify({passed:true,stage,errors}));
}catch(error){if(stage!=='统一认证')await page.screenshot({path:'.runtime/qa/failure.png'});console.error(JSON.stringify({passed:false,stage,messages:await Promise.all(page.frames().map(async frame=>({path:new URL(frame.url()).pathname,messages:await frame.evaluate(()=>window.__fileMessages||[]).catch(()=>[])}))),detail:error.message.split('\n')[0],pathname:new URL(page.url()).pathname,errors}));process.exitCode=1;}
finally{if(folderId){try{const session=await(await context.request.get('http://127.0.0.1:4301/api/session')).json();csrf=session.csrfToken;const headers={'X-CSRF-Token':csrf,Origin:'http://127.0.0.1:4301'};for(const id of [folderId,desktopFileId].filter(Boolean)){const soft=await context.request.delete(`http://127.0.0.1:4301/api/apps/files/entries/${id}`,{headers});const hard=await context.request.delete(`http://127.0.0.1:4301/api/apps/files/entries/${id}/permanent`,{headers});console.log(JSON.stringify({cleanup:[soft.status(),hard.status()]}));}}catch{console.log('测试目录清理失败，请仅按测试目录 ID 重试');}}await browser.close();}






