import { chromium, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
expect.configure({timeout:15000});
const account=JSON.parse(await readFile('../mg-desktop-one/.runtime/local/account.json','utf8'));
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext(),page=await context.newPage();
let folderId,headers,stage='统一认证';const errors=[];page.on('pageerror',error=>errors.push(error.message.split('\n')[0]));
try{
 await page.goto('http://127.0.0.1:14351/my-files');await page.getByRole('textbox',{name:'登录账号',exact:true}).fill(account.username);await page.getByRole('textbox',{name:'登录密码',exact:true}).fill(account.password);await page.getByRole('button',{name:'登 录',exact:true}).click();await page.waitForURL('http://127.0.0.1:14351/my-files');
 const session=await(await context.request.get('http://127.0.0.1:4301/api/session')).json();headers={'X-CSRF-Token':session.csrfToken,Origin:'http://127.0.0.1:4301'};const listing=await(await context.request.get('http://127.0.0.1:4301/api/apps/files/entries')).json();folderId=(await(await context.request.post('http://127.0.0.1:4301/api/apps/files/folders',{headers,data:{parentId:listing.rootId,name:`重试验证-${Date.now()}`}})).json()).id;
 await page.goto(`http://127.0.0.1:14351/my-files/${folderId}`);await expect(page.getByRole('button',{name:'上传文件',exact:true})).toBeEnabled();
 stage='Uppy失败重试';let rejected=false;await page.route('**/api/apps/files/uploads?*',route=>{if(!rejected){rejected=true;return route.fulfill({status:503,json:{message:'测试模拟临时不可用'}});}return route.continue();});await page.locator('input[type=file]').setInputFiles({name:'失败后重试.txt',mimeType:'text/plain',buffer:Buffer.from('retry verified')});await expect(page.getByRole('button',{name:'重试',exact:true})).toBeVisible();const upload=page.waitForResponse(r=>r.url().includes('/api/apps/files/uploads?')&&r.status()===201);await page.getByRole('button',{name:'重试',exact:true}).click();const id=(await(await upload).json()).id;await expect(page.locator('.file-grid').getByText('失败后重试.txt',{exact:true})).toBeVisible();
 stage='注册重命名intent';await page.goto(`http://127.0.0.1:14351/my-files/desktop?intent=rename&open=${id}`);await expect(page.getByRole('textbox',{name:'名称',exact:true})).toHaveValue('失败后重试.txt');await expect(page.locator('.preview-body')).toHaveCount(0);await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.locator('.el-overlay:visible')).toHaveCount(0);
 stage='注册移动intent';await page.goto(`http://127.0.0.1:14351/my-files/desktop?intent=move&open=${id}`);await expect(page.getByRole('combobox',{name:'目标文件夹',exact:true})).toBeEnabled();await expect(page.locator('.preview-body')).toHaveCount(0);await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.locator('.el-overlay:visible')).toHaveCount(0);
 stage='受保护桌面菜单';await page.goto('http://127.0.0.1:14351/my-files');await page.locator('.file-tile').filter({has:page.getByText('桌面',{exact:true})}).click({button:'right'});await expect(page.getByRole('menuitem',{name:'打开文件夹',exact:true})).toBeVisible();for(const action of ['重命名','移动','移到回收站'])await expect(page.getByRole('menuitem',{name:action,exact:true})).toHaveCount(0);await page.keyboard.press('Escape');expect(errors).toEqual([]);console.log(JSON.stringify({passed:true,stage,errors}));
}catch(error){if(stage!=='统一认证')await page.screenshot({path:'.runtime/qa/extras-failure.png'});console.error(JSON.stringify({passed:false,stage,detail:error.message.split('\n')[0],errors}));process.exitCode=1;}
finally{if(folderId&&headers){const a=await context.request.delete(`http://127.0.0.1:4301/api/apps/files/entries/${folderId}`,{headers});const b=await context.request.delete(`http://127.0.0.1:4301/api/apps/files/entries/${folderId}/permanent`,{headers});console.log(JSON.stringify({cleanup:[a.status(),b.status()]}));}await browser.close();}

