export { createDesktopApplication } from './desktop-sdk/src/application';
export { createApplicationClient, ApplicationRequestError, serviceRequestUrl, serviceInvocationUrl } from './services/client';
export type { ServiceManifest, ServiceOperation } from './services/contracts';
export { default as PageFrame } from './PageFrame.vue';
export { default as NavigationToggle } from './NavigationToggle.vue';
export { default as NavigationFooter } from './NavigationFooter.vue';
export { default as ApplicationShell } from './ApplicationShell.vue';
export { default as ConfiguredApplicationShell } from './ConfiguredApplicationShell.vue';
export { default as PlatformIcon } from './PlatformIcon.vue';
export { default as ApplicationHeader } from './ApplicationHeader.vue';
export { default as ApplicationIcon } from './ApplicationIcon.vue';
export { default as ConfiguredApplicationHeader } from './ConfiguredApplicationHeader.vue';
export { applyApplicationDocument, applicationDocumentTitle } from './config/document';
export { applicationPresentation, platformCatalog } from './config/catalog';
export { default as PageHeading } from './PageHeading.vue';
export { default as ContentPanel } from './ContentPanel.vue';
export { createPlatformSession } from './auth/session';
export { defaultPlatformOrigin, configurePlatformOrigin } from './auth/platform-origin';
export { loadApplicationConfig } from './config/application';
export type { ApplicationConfig, ApplicationBrandConfig, ApplicationPageConfig, ApplicationNavigationConfig, ApplicationNavigationGroupConfig, ApplicationNavigationParentConfig, ApplicationRegistryKeys } from './config/application';
export { default as ApplicationNavigation } from './ApplicationNavigation.vue';
export { createApplicationDialogs } from './dialogs/application-dialogs';
export type { ApplicationDialogDefinition, ApplicationDialogController, ApplicationDialogs } from './dialogs/application-dialogs';
export { default as ApplicationDialogHost } from './ApplicationDialogHost.vue';
export type { DesktopDialogDefinition, DesktopDialogContext, DesktopDialogResult } from './desktop-contracts/src/index';
export {compareServiceVersions} from './services/versions';
export type {ServiceChange} from './services/versions';
export {compareContractVersions,contractOperation,contractReference} from './services/openapi';
export type {ServiceContract,ContractChange} from './services/openapi';
