<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus, Refresh } from '@element-plus/icons-vue';
import { api, type ManagedRole, type ManagedUser } from '../api/client';
const router = useRouter(), roles = ref<ManagedRole[]>([]), users = ref<ManagedUser[]>([]), loading = ref(false), saving = ref(false), error = ref('');
const dialog = ref(false), membersDialog = ref(false), form = reactive({ id: '', key: null as string|null, name: '', description: '' }), selected = ref(''), memberId = ref('');
const current = computed(() => roles.value.find(r => r.id === selected.value));
const members = computed(() => users.value.filter(u => current.value?.members.some(m => m.userId === u.id)));
const available = computed(() => users.value.filter(u => !current.value?.members.some(m => m.userId === u.id)));
async function load() { loading.value = true; error.value = ''; try { [roles.value, users.value] = await Promise.all([api.roles(), api.users()]); } catch (e) { error.value = (e as Error).message; } finally { loading.value = false; } }
function edit(role?: ManagedRole) { Object.assign(form, role ? { id: role.id, key: role.key, name: role.name, description: role.description } : { id: '', key: null, name: '', description: '' }); dialog.value = true; }
async function save() { if (saving.value || !form.name.trim()) return; saving.value = true; try { const body = { name: form.name, description: form.description }; if (form.id) await api.updateRole(form.id, body); else await api.createRole(body); dialog.value = false; await load(); ElMessage.success('角色已保存'); } catch (e) { ElMessage.error((e as Error).message); } finally { saving.value = false; } }
async function remove(role: ManagedRole) { try { await ElMessageBox.confirm(`删除角色“${role.name}”？必须先清空成员及应用授权。`, '删除角色', { type: 'warning' }); await api.deleteRole(role.id); await load(); } catch (e) { if (e !== 'cancel' && e !== 'close') ElMessage.error((e as Error).message); } }
async function member(userId: string, enabled: boolean) { if (saving.value) return; saving.value = true; try { await api.roleMember(selected.value, userId, enabled); memberId.value = ''; await load(); } catch (e) { ElMessage.error((e as Error).message); } finally { saving.value = false; } }
onMounted(load);
</script>
<template><div class="primary-page users-page" v-loading="loading"><div class="primary-page-heading"><div><h1>角色管理</h1><p>统一维护角色成员和应用授权。平台管理员为内置角色，普通角色不会因名称获得平台管理能力。</p></div><div><el-button :icon="Refresh" @click="load">刷新</el-button><el-button type="primary" :icon="Plus" @click="edit()">新增角色</el-button></div></div>
  <el-alert v-if="error" :title="error" type="error" :closable="false" />
  <section class="table-wrap table-panel"><el-table :data="roles" height="100%"><el-table-column label="角色" min-width="180"><template #default="{row}"><strong>{{ row.name }}</strong><el-tag v-if="!!row.key" size="small" effect="plain">内置角色</el-tag><small class="subtext">{{ row.description || '暂无说明' }}</small></template></el-table-column><el-table-column label="成员" width="100"><template #default="{row}">{{ row.members.length }} 人</template></el-table-column><el-table-column label="应用授权" width="120"><template #default="{row}">{{ row.applications.filter((a:any) => a.enabled).length }} 个</template></el-table-column><el-table-column label="操作" min-width="310"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link type="primary" @click="selected=row.id;membersDialog=true">成员分配</el-button><el-button link type="primary" @click="router.push({path:'/applications',query:{role:row.id}})">应用授权</el-button><el-button link type="danger" :disabled="!!row.key" :title="!!row.key?'内置角色不可删除':'删除角色'" @click="remove(row)">删除</el-button></template></el-table-column><template #empty><el-empty description="暂无角色" /></template></el-table></section>
  <el-dialog v-model="dialog" :title="form.id ? '编辑角色' : '新增角色'" width="520px" :close-on-click-modal="false"><el-form label-position="top" @submit.prevent="save"><el-form-item label="角色名称" required><el-input v-model="form.name" maxlength="80" :disabled="form.key==='platform-admin'" /></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" maxlength="500" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!form.name.trim()" @click="save">保存</el-button></template></el-dialog>
  <el-dialog v-model="membersDialog" :title="`${current?.name || '角色'} · 成员分配`" width="640px" :close-on-click-modal="false"><div class="role-add-member"><el-select v-model="memberId" filterable placeholder="选择用户" aria-label="添加角色成员"><el-option v-for="u in available" :key="u.id" :label="u.displayName" :value="u.id" /></el-select><el-button type="primary" :disabled="!memberId || saving" @click="member(memberId,true)">添加成员</el-button></div><el-table :data="members" max-height="400"><el-table-column prop="displayName" label="用户" /><el-table-column prop="username" label="账号" /><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="danger" :disabled="saving" @click="member(row.id,false)">移除</el-button></template></el-table-column></el-table><template #footer><el-button @click="membersDialog=false">完成</el-button></template></el-dialog>
</div></template>
<style scoped>.role-add-member{display:flex;gap:12px;margin-bottom:16px}.role-add-member .el-select{flex:1}</style>
