<script setup lang="ts">
import { identityPresentation } from '../presentation';
import { computed,onMounted,reactive,ref } from 'vue';
import { Plus,Refresh,Search } from '@element-plus/icons-vue';import { ElMessage,ElMessageBox } from 'element-plus';
import { api,send,request,type ManagedUser,type ManagedRole } from '../api/client';import { user as session } from '../session';
const roles=ref<ManagedRole[]>([]);
const users=ref<ManagedUser[]>([]),loading=ref(false),error=ref(''),query=ref(''),status=ref('all'),page=ref(1),dialog=ref(false),saving=ref(false),editing=ref<ManagedUser|null>(null);
const filtered=computed(()=>users.value.filter(u=>(status.value==='all'||u.status===status.value)&&`${u.displayName} ${u.username||''} ${u.departmentName||''}`.toLowerCase().includes(query.value.toLowerCase())));
const rows=computed(()=>filtered.value.slice((page.value-1)*12,page.value*12));
const form=reactive({username:'',displayName:'',departmentName:'',password:'',roleIds:[] as string[]});
const binding=ref<ManagedUser|null>(null),bindingType=ref('wecom'),external=ref('');
async function load(){loading.value=true;error.value='';try{[users.value,roles.value]=await Promise.all([api.users(),api.roles()])}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
function edit(target:ManagedUser|null){editing.value=target;Object.assign(form,{username:target?.username||'',displayName:target?.displayName||'',departmentName:target?.departmentName||'',password:'',roleIds:target?.roles?.map(role=>role.id)||[]});dialog.value=true}
async function save(){if(saving.value)return;if(!form.displayName.trim())return ElMessage.warning('请输入姓名');if(!editing.value&&(!/^[a-z0-9._-]{3,50}$/.test(form.username)||form.password.length<15))return ElMessage.warning('账号需为 3–50 位字母、数字或 ._-，密码至少 15 位');saving.value=true;try{if(editing.value)await api.updateUser(editing.value.id,{displayName:form.displayName.trim(),departmentName:form.departmentName.trim(),roleIds:form.roleIds});else await api.createUser({...form,displayName:form.displayName.trim()});dialog.value=false;await load();ElMessage.success(editing.value?'资料已保存，将同步至授权应用':'身份已创建，请前往应用授权分配访问权限')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false;form.password=''}}
async function toggle(target:ManagedUser){try{await ElMessageBox.confirm(target.status==='active'?`停用 ${target.displayName} 后，所有接入应用将拒绝其访问。历史业务数据保留。`:`恢复 ${target.displayName} 的统一身份？`,'调整账号状态',{type:'warning'});await api.updateUser(target.id,{status:target.status==='active'?'disabled':'active'});await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}}
async function reset(target:ManagedUser){try{const result=await ElMessageBox.prompt('请输入至少 15 位的新密码。重置后该用户需要重新登录。',`重置 ${target.displayName} 的密码`,{inputType:'password',inputValidator:v=>(v?.length>=15&&v.length<=128)||'密码需为 15–128 位'});await send(`/users/${target.id}/reset-password`,{password:result.value});ElMessage.success('密码已重置')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}}
function openBinding(target:ManagedUser){binding.value=target;bindingType.value='wecom';external.value=''}
async function bind(){if(!binding.value||saving.value||!external.value.trim())return;saving.value=true;try{await send(`/users/${binding.value.id}/${bindingType.value==='wecom'?'wecom-identities':'zentao-identity'}`,bindingType.value==='wecom'?{externalUserId:external.value.trim()}:{account:external.value.trim()});binding.value=null;await load();ElMessage.success('登录身份已关联')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function unbind(){const target=binding.value;const identity=target?.wecomIdentities[0];if(!target||!identity)return;try{await ElMessageBox.confirm('解除绑定后将撤销该员工现有会话，扫码登录需要重新关联身份。','解除企业微信绑定',{type:'warning'});await send(`/users/${target.id}/wecom-identities/${identity.id}/unbind`,{});binding.value=null;await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}}
async function sync(){try{await ElMessageBox.confirm('从企业微信应用可见范围同步员工资料。完成后请核对身份，再授予业务应用权限。','同步企业微信',{type:'info'});loading.value=true;const result=await send('/users/wecom-sync',{});await load();ElMessage.success(`读取 ${result.total} 位成员，新增 ${result.created} 位，冲突 ${result.conflicts} 位`)}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{loading.value=false}}
onMounted(load);
</script>
<template><div class="primary-page users-page"><div class="primary-page-heading"><div><h1>员工身份</h1><p>集中维护员工账号与登录身份，资料自动同步到授权应用。</p></div><div class="primary-page-actions"><el-button :icon="Refresh" :disabled="loading" @click="load">刷新</el-button><el-button @click="sync" :disabled="loading">同步企业微信</el-button><el-button type="primary" :icon="Plus" @click="edit(null)">创建身份</el-button></div></div><el-alert v-if="error" :title="error" type="error" :closable="false"/>
  <section class="table-wrap table-panel"><div class="users-list-toolbar table-toolbar"><el-input v-model="query" :prefix-icon="Search" clearable placeholder="搜索姓名、账号或部门" aria-label="搜索员工" @input="page=1"/><el-select v-model="status" aria-label="账号状态" @change="page=1"><el-option label="全部状态" value="all"/><el-option label="启用" value="active"/><el-option label="停用" value="disabled"/></el-select><span class="count">共 {{filtered.length}} 位员工</span></div>
    <el-table height="100%" :data="rows" v-loading="loading" row-key="id"><el-table-column label="员工" min-width="200"><template #default="{row}"><div class="person-cell"><el-avatar :size="34">{{row.displayName.slice(0,1)}}</el-avatar><div><strong>{{row.displayName}}</strong><small>{{row.username||'待设置登录账号'}}</small></div></div></template></el-table-column><el-table-column label="部门" min-width="140"><template #default="{row}">{{row.departmentName||'未设置'}}</template></el-table-column><el-table-column label="角色" min-width="200"><template #default="{row}"><div class="tags"><el-tag v-for="role in row.roles || []" :key="role.id" size="small" effect="plain" :type="role.key==='platform-admin'?'primary':'info'">{{role.name}}{{role.key==='platform-admin'?' · 内置':''}}</el-tag><span v-if="!row.roles?.length" class="muted">未分配</span></div></template></el-table-column><el-table-column label="登录身份" min-width="150"><template #default="{row}"><div class="tags"><el-tag v-if="row.wecomBound" size="small" type="success" effect="light">企业微信</el-tag><el-tag v-if="row.zentaoIdentities?.length" size="small" effect="light">禅道</el-tag><span v-if="!row.wecomBound&&!row.zentaoIdentities?.length" class="muted">账号密码</span></div></template></el-table-column><el-table-column label="状态" width="85"><template #default="{row}"><span :class="row.status==='active'?'active-text':'muted'">{{row.status==='active'?'启用':'停用'}}</span></template></el-table-column><el-table-column label="操作" width="255" fixed="right"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-dropdown @command="(command:string)=>command==='bind'?openBinding(row):command==='reset'?reset(row):toggle(row)"><el-button link type="primary">管理</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="bind">登录身份</el-dropdown-item><el-dropdown-item command="reset">重置密码</el-dropdown-item><el-dropdown-item command="toggle" :disabled="row.id===session?.userId">{{row.status==='active'?'停用账号':'启用账号'}}</el-dropdown-item></el-dropdown-menu></template></el-dropdown><router-link :to="{path:'/applications',query:{user:row.id}}" class="text-link">应用授权</router-link></template></el-table-column><template #empty><el-empty description="没有符合条件的员工" :image-size="70"/></template></el-table><div class="pagination"><el-pagination v-model:current-page="page" :total="filtered.length" :page-size="12" layout="total, prev, pager, next"/></div>
  </section><el-dialog v-model="dialog" :title="editing?'编辑员工资料':'创建统一身份'" width="520px" :close-on-click-modal="false" :show-close="!saving" @closed="form.password=''"><el-form label-position="top" @submit.prevent="save"><el-form-item label="姓名" required><el-input v-model="form.displayName" maxlength="100" :disabled="saving" placeholder="请填写真实姓名"/></el-form-item><div class="form-grid"><el-form-item label="登录账号" :required="!editing"><el-input v-model="form.username" :disabled="Boolean(editing)||saving" maxlength="50" placeholder="字母、数字或 ._-"/></el-form-item><el-form-item label="部门"><el-input v-model="form.departmentName" maxlength="100" :disabled="saving"/></el-form-item></div><el-form-item v-if="!editing" label="初始密码" required><el-input v-model="form.password" type="password" show-password autocomplete="new-password" maxlength="128" placeholder="至少 15 位字符" :disabled="saving"/></el-form-item><el-form-item label="角色"><el-select v-model="form.roleIds" multiple filterable class="full-width" :disabled="saving" aria-label="用户角色"><el-option v-for="role in roles" :key="role.id" :label="role.name+(role.key==='platform-admin'?'（内置）':'')" :value="role.id"/></el-select><p class="form-hint">平台管理员通过统一角色分配，还需获得{{identityPresentation.name}}应用授权。业务应用访问按角色或用户直接授权生效。</p></el-form-item></el-form><template #footer><el-button :disabled="saving" @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  <el-dialog :model-value="Boolean(binding)" :title="`${binding?.displayName||''} · 登录身份`" width="520px" @close="binding=null"><template v-if="binding"><div class="identity-bindings"><p>企业微信：{{binding.wecomIdentities[0]?.externalUserId||'未绑定'}}</p><p>禅道：{{binding.zentaoIdentities?.[0]?.account||'未绑定'}}</p><el-button v-if="binding.wecomBound" link type="danger" @click="unbind">解除企业微信绑定</el-button></div><el-form label-position="top" @submit.prevent="bind"><el-form-item label="身份来源"><el-radio-group v-model="bindingType" @change="external=''"><el-radio-button value="wecom">企业微信</el-radio-button><el-radio-button value="zentao">禅道</el-radio-button></el-radio-group></el-form-item><el-form-item :label="bindingType==='wecom'?'企业微信成员 UserID':'禅道账号'"><el-input v-model="external" maxlength="128" :disabled="saving"/></el-form-item><p class="form-hint">核对身份属于同一员工后再关联，避免错绑他人账号。</p></el-form></template><template #footer><el-button @click="binding=null">取消</el-button><el-button type="primary" :loading="saving" :disabled="!external.trim()" @click="bind">关联身份</el-button></template></el-dialog>
</div></template>


