import {createApp} from 'vue';
import {createRouter,createWebHistory} from 'vue-router';
import ElementPlus from 'element-plus';
import zhCn from 'element-plus/es/locale/lang/zh-cn';
import {applyApplicationDocument,loadApplicationConfig} from '@mg-inside/frontend';
import 'element-plus/dist/index.css';
import '@mg-inside/frontend/shell.css';
import '@mg-inside/frontend/layout.css';
import '@mg-inside/frontend/embedded.css';
import '@mg-inside/frontend/overlays.css';
import './style.css';
import input from '../application.json';
import App from './App.vue';
import {desktop} from './api';
export const application=loadApplicationConfig(input,{components:['resources'],assets:[]});
const router=createRouter({history:createWebHistory(import.meta.env.BASE_URL),routes:[{path:'/',redirect:application.defaultPath},...application.pages.map(p=>({path:p.path,component:{render:()=>null},meta:{title:p.title}})),{path:'/:pathMatch(.*)*',redirect:application.defaultPath}]});
router.afterEach(to=>{applyApplicationDocument(application,{},String(to.meta.title||application.name));desktop.setTitle(application.name);desktop.routeChanged(to.fullPath)});
desktop.configure({onNavigate:async path=>{await router.push(path)}});
createApp(App).use(router).use(ElementPlus,{locale:zhCn}).mount('#app');
